


List<String> Repositoriopreguntas(String inv) {

    switch (inv) {
      case "/inventario_autoevaluacion_aptitudes":
        return aptitudes;
      case "/inventario_interes_ocupacional":
        return ocupacional;
      case "/inventario_preferencias_universitarias":
        return universitarias;
      default:
        return ["Tipo de lista de preguntas no válido"];
    }
}

int tamanoInventario(String inv) => Repositoriopreguntas(inv).length;

  final aptitudes = [
    "Comprender con facilidad cómo se conectan algunos elementos, por ejemplo, las relaciones entre los órganos del cuerpo humano, las relaciones que se dan entre los elementos de una computadora.",
    "Decorar, con pincel fino, pequeñas figuras humanas (pintar la boca, ojos, cejas, etc.).",
    "Ayudar a un especialista en diseño de juegos electrónicos a realizar juegos entables que sean de entretenimiento numérico.",
    "Darte cuenta cuando un conferencista, al estar presentando su tema, lo expone de manera demasiado elemental.",
    "Dar buenas ideas a un grupo de vendedores (que van casa por casa) acerca de cómo convencer a los clientes para comprar el producto ofrecido.",
    "Aprender las partes y funciones de un velero, así como su operación y armado.",
    "Enseñar a alguien durante un largo período, sin interrumpirle, sin impacto, y aceptar lo como es.",
    "Distribuir las funciones y responsabilidades a los miembros de un grupo o equipo de trabajo, procurando que todos se sientan lo más conformes con esta distribución.",
    "Tomar un curso sobre comunicación no verbal en un pequeño almacén, mediante una computadora sencilla, y aprender fácilmente.",
    "Vencer las diferencias entre la música clásica, la popular y la moderna.",
    "Diseñar el logotipo de una empresa.",
    "Armar rompecabezas complicados (cada cubo de Rubik, por ejemplo).",
    "Hacer un análisis de la estructura financiera de la línea y sin ayuda de reglas.",
    "Reconocer tus errores cuando discutes con otra persona, aunque esto no sea de tu total agrado o tengo puntos contrarios a los tuyos.",
    "Diseñar una revista de pasatiempos, con problemas sencillos, con base en relaciones numéricas o químicas algebraicas.",
    "Explicar fácilmente, al terminar una lectura (sobre cualquier género de novelas), cómo se relacionan los personajes o cómo se desarrolla la trama.",
    "Idear un sistema rápido en cronista deportivo, para que gráficamente pueda organizar datos deportivos tales como: los promedios de bateo, bases robadas, home runs, etc., de una temporada.",
    "Ser presidente de un club social y decidir a cada uno de los miembros de la mesa directiva sus tareas y sin dudar, ser efectivos, de forma precisa.",
    "Aprender las partes y funciones de un planeador, así como su operación y armado.",
    "Inventar un método para el trabajo de publicistas sobre cómo presentar un producto en un comercial de TV o de radio.",
    "Entender las nomenclaturas químicas o el funcionamiento estructural de todos los órganos del cuerpo humano.",
    "Diseñar figuras geométricas en tres dimensiones, variando las posiciones y perspectivas.",
    "Ver técnicas para realizar pinturas en acuarela y óleo.",
    "Aprender el manejo de la herramienta propia para modelar y esculpir barro, trabajar vidrio, porcelana, latón y piel, de manera artesanal.",
    "Darte cuenta fácilmente si el profesor omitió un dato o punto necesario para la resolución de un problema durante el examen de matemáticas y saber con precisión lo que falta.",
    "Idear un sistema para pequeñas tiendas de regalos, en el que puedan llevar un inventario de la existencia de sus productos.",
    "Hacer un buen resumen de cualquier libro o escrito que hayas leído, con toda la información relevante bien organizada.",
    "Tratar por igual a todos sin distinción de clase o condición social.",
    "Operar y dar mantenimiento a un tractor agrícola, incluyendo sus implementos.",
    "Cumplir, a la perfección, una tarea asignada por tus padres, un profesor o jefe de trabajo.",
    "Aprender a leer, interpretar y combinar notas musicales.",
    "Descubrir bellamente el aparador de una tienda o un puesto de una feria o verbena.",
    "Reconocer en una persona que no sea de tu agrado, sus fortalezas, sus virtudes y sus aciertos.",
    "Comentar en un programa televisivo de la universidad, las ventajas y desventajas de las plantillas que aspiran a dirigir la sociedad de alumnos, y argumentar a favor de una de ellas.",
    "Sacar astillas de la piel con pinzas para las cejas (en el primer intento).",
    "Aprender a usar métodos científicos para profundizar en el conocimiento de las relaciones que, por ejemplo, hay entre los seres vivos que integran el ecosistema, los cambios químicos que se dan en la naturaleza, etcétera.",
    "Entender fácilmente el uso de un compás, y poder explicar fácilmente todas sus funciones para ver las cosas desde esa perspectiva (aunque no sea grande como punto de vista si tu compañero).",
    "Entender fácilmente artículos de revistas que versan sobre investigación en las ciencias naturales, como química, biología, geofísica, etcétera.",
    "Dar información muy completa de cualquier tema que te adhieran revisar (medidas de errores en fichas, metas que se proponen, pasos, puntos omitidos, etc.).",
    "Instalar, operar y darle mantenimiento a una computadora casera con sólo consultar el manual o instructivo de operaciones.",
    "Identificar errores ortográficos, en la organización de las párrafos y errores de redacción en cualquier escrito, aún cuando sea ilegible.",
    "Darle buenas sugerencias a un banco pequeño acerca de cómo organizar los departamentos de atención al público con el fin de que sus clientes no hagan largas colas de espera.",
    "Darte cuenta cuando un profesor comete errores al estar explicando al grupo la solución (procedimiento) de un problema de matemáticas.",
    "Soldar los transistores de un radio sin derramar soldadura, ni tocar con el soldador partes cercanas al transistor.",
    "Sugerir a alguien que va a construir su casa la forma en que debería o la distribución de la misma, aprovechando al máximo todos los espacios.",
    "Aprender las técnicas en el departamento de almacén comercial (libros, música, ferretería, etc.) y manejar tal vez períodos las ventas y consumo por los clientes que lo visitan.",
    "Aprender a ejecutar, con dominio, uno o varios instrumentos musicales.",
    "Recordar, detalladamente, las indicaciones dadas por alguien para llegar a una dirección desconocida.",
    "Aprender a diferenciar lo bello de la pintura de los grandes clásicos, en relación con otras pinturas.",
    "Dar a una familia consejos prácticos acerca de planear que sí compleméntente cambie ciertas actitudes de ellos.",
    "Comprender todo tipo y tener a tu lado, como evolucionan y se transforman los seres vivos, de acuerdo con las teorías evolucionistas de Darwin, o explicar en qué consisten las especies protegidas o seleccionamiento de tiempos químicos como lluvia.",
    "Fungir como tercero en un conflicto (sin tomar partido por las personas involucradas) y conciliar a las partes en pugna aunque una de ellas te simpatice mucho.",
    "Supervisar y corregir la redacción de un discurso que alguien competente tuvo vaya a dirigir a una asamblea.",
    "Aprender el sistema de clasificación que se utiliza para los archivos de la Nación.",
    "Dibujar a lápiz el rostro de las personas, siguiendo ciertas técnicas.",
    "Enseñar algunos tipos en grupos muy pequeñas, sin que lo intentes más de tres veces.",
    "Aplicar conocimientos matemáticos y principios de la ciencia para el diseño de puentes que no haya infringido cuando esa aplicación implique la expansión del grupo de alguien muy avanzado.",
    "Inventar algo útil para los aerospacios y artículos de la revista ¡Mecánica Popular!",
    "Recordar, durante una segunda visita, el lugar de una colonia intrincada, en donde vive alguien conocido.",
    "Aprender a complementar los distintos instrumentos musicales en la ejecución de una pieza.",
    "Aprender técnicas para construir maquetas y objetos de cualquier tipo a escala. (Por ejemplo, un avión, un ayuda de campo con material).",
    "Entender fácilmente la explicación de un armero sobre cómo funciona cierto tipo de armamento militar, ya sea fusiles, ametralladoras o artillería en miniatura.",
    "Prever e identificar las consecuencias para ti y para los demás (de manera detallada y precisa) de las decisiones que tomes.",
    "Colocar sin errores, con pinzas pequeñas, los engranes de un reloj.",
    "Explicar los factores por el material a un grupo de compañeros menos aventajados, de manera más sencilla que el profesor.",
    "Aprender y manejar el sistema de clasificación y localización de piezas en una refaccionaria de automóviles.",
    "Explicar de forma clara y lógica a un grupo de personas, con las mismas palabras y con ejemplos ilustrativos, el manejo de algún aparato técnico que tú ya domines.",
    "Comprender con facilidad cómo una persona cercana a ti ve desde su interior el mundo. Comprender también los sentimientos que tiene y sus expectativas.",
    "Aplicar las leyes y teorías de la química o de la biología cuando resolvemos un problema de matemáticas.",
    "Generar argumentos, ante un auditorio, a favor de tu punto de vista o de algún proyecto.",
    "Aprender a hacer arreglos musicales.",
    "Resolver problemas de matemáticas y seleccionar las fórmulas y procedimientos necesarios de manera precisa y fácil.",
    "Apretar, con un pequeño desarmador, los tornillos de los anteojos.",
    "Dar una conferencia sobre un tema de computación tuya tonga éxito en una campaña política o en cualquier actividad.",
    "Aprender con facilidad a afinar automóviles o a dar mantenimiento y reparación a aparatos caseros como: podadoras de pasto, calentadores de gas, estufas, etcétera.",
    "Dar ideas al párroco o ministro de tu iglesia acerca de cómo mejorar sus sermones o sus actividades espirituales.",
    "Obtener fácilmente conclusiones a una síntesis de algún trabajo que hayas encargado el profesor de biología o de química sobre cualquier tema.",
    "Darte cuenta de los deseos, preocupaciones o sentimientos de alguien, solo por ver sus gestos y movimientos.",
    "Estudiar e interpretar las instrucciones y las preguntas de un examen.",
    "Diseñarle a una pequeña ferretería un sistema para localizar rápidamente los productos que el cliente pide.",
    "Combinar materiales de todo tipo (yeso, madera, pinturas) para hacer objetos de ornato, como floreros, ceniceros, pisapapeles, etcétera.",
    "Armar aparatos de radio, televisión, amplificadores, grabadoras, etcétera.",
    "Aprender con facilidad a escribir y arreglar canciones y composiciones musicales.",
    "Distinguir errores en las perspectivas de los dibujos.",
    "Hacerle ver a un grupo que discute cosas que no han considerado o puntos omitidos que pueden influir en sus opiniones sobre lo discutido.",
    "Construir, en un taller de aficionados, artefactos sencillos como un velero, un planeador, etcétera.",
    "Lograr entusiasmar a un grupo de trabajo que se encuentra pesimista en cuanto a las metas de trabajo por lograr.",
    "Enhebrarse rápidamente un collar de perlas.",
    "Darte cuenta de inmediato de cuál es el error de un compañero que no puede resolver correctamente un problema de matemáticas.",
    "Participar con un diseño tuyo, con probabilidades de ganar, en un concurso de la escuela cuyo objetivo o meta sea el de proponer un sistema de clasificación para los expedientes de los estudiantes.",
    "Darte cuenta de inmediato cuando un profesor se aplica un examen con errores de contenido o en la clasificación de las preguntas.",
    "Predecir la forma en que un conocido tuyo va a actuar, lo que va a decir y a pensar en una situación dada.",
    "Comprender la relación entre estructuras y funciones de los órganos del cuerpo humano; establecer cómo se relacionan todos los sistemas, o hacer esto mismo con plantas o animales.",
    "Diseñar la decoración de un hogar o una oficina.",
    "Hacerle a un carpintero, detalladamente (con ángulos, medidas, superficies, etc.), un diseño sobre el tipo de muebles que necesitas hacer.",
    "Entender los principios (cómo funcionan las hipótesis, como relacionaciones, como componentes, instrumentos, cómo operan, etcétera) de todo lo que un químico o algún biólogo famoso logra llegar a sus descubrimientos.",
    "Darte cuenta rápidamente cuando alguien está pasando por un mal momento y necesita de tu ayuda sin que te lo pida.",
    "Escribir sin galón teatral o alguna pequeña obra, relacionando y ordenando correctamente los diálogos de los personajes, las escenas, etcétera.",
    "Mejorar el procedimiento de inscripciones en la escuela, creando uno más rápido, más fácil, práctico y eficiente.",
    "Prestar ayuda al profesor de matemáticas para plantear problemas de repaso referentes a toda la materia.",
    "Pegar piedras preciosas en un collar, viendo a través de una lupa.",
    "Hacer que todos los miembros de un grupo de trabajo que tienes, sin sentirse presionado o perseguido.",
    "Ayudarte fácilmente a que un curso la reparación de productos electrónicos, mecánicos, etc., y que te quede fundamenta.",
    "Aprender a ser un buen orador mediante un curso rápido y sencillo.",
    "Darte cuenta cuando alguien tiene un error en la ejecución de una pieza musical.",
    "Dibujar figuras en detalles complicadas, con instrumentos, etc.) de las.",
    "Ejemplificar fácilmente cómo se pueden observar en la vida cotidiana las leyes y principios de la biología o de la química.",
    "Saber identificar el momento oportuno para dar un consejo, empezar una conversación, o hacer una pregunta a alguien con quien no se puede platicar muy fácilmente.",
    "Dirigir un grupo musical que interprete melodías de moda.",
    "Hacer fácil y rápidamente composición escritas, unas oraciones, párrafos, títulos o subtítulos, según todas las desedan.",
    "Aprender como computar las datos (nóminas, inventarios, egresos, ingresos, etc.), de un pequeño comercio.",
    "Diseñar putos de examen con problemas y ejercicios de matemáticas para la clase.",
    "Interpretar muy bien al sello de la música que más te gusta, tocas.",
    "Armar y desarraigar rapidamente y sin errores un reloj de pulso.",
    "Identificar las limitantes físicas de los miembros de un grupo de trabajo para asignarles responsabilidades en una tarea determinada.",
    "Entender fácilmente la aplicación de un aparato no eléctrico para soltar molino sobre la forma en que se combina la electrónica, la electricidad y la mecánica, en la construcción del armamento de la aviación.",
    "Preparar y dar un discurso a un auditorio acerca de la necesidad de cuidar la Tierra de forma que los futuros generados no se vean en el descuido de deterioro ambiental, o acerca de tomar las medidas necesarias.",
    "Recortar con facilidad el ritmo de las piezas musicales que más te agradan.",
    "Reducir con facilidad los lugares de un estacionamiento de coches en forma tal que quepan más autos en la capa y finales cada espacio.",
    "Decorar objetos cerámicos, de piel, de madera, de barro, etcétera."
  ];
  final ocupacional = [
    "Ser comentarista de temas diversos en un programa de televisión.",
    "Leer una revista en donde se explique cómo se relacionan los seres vivos en el ecosistema.",
    "Coleccionar revistas como las de Mecánica popular y Ármelo usted mismo.",
    "Vivir temporadas largas en las rancherías y en las labores o cultivos para realizar trabajos diversos.",
    "Visitar una exposición donde se exhiben residuos de meteoritos o rocas de todo tipo provenientes del espacio, de grutas famosas, del fondo del océano, etcétera.",
    "Participar en campañas cuyo fin es concientizar a la población marginada de la necesidad de organizarse para crear cooperativas de consumo.",
    "Leer biografías u obras de literatos famosos.",
    "Observar en una biblioteca cómo clasifican sus libros, y conocer el sistema de clasificación.",
    "Participar en un grupo musical dedicado a rescatar e interpretar música no comercial.",
    "Colaborar con el grupo de \"Amigos de la Tierra\" (biólogos, químicos, bioquímicos, médicos, etc.), en la recolección de datos estadísticos que demuestren la necesidad de cuidar nuestro mundo.",
    "Ser parte de un jurado que califique, en un concurso, la mejor composición escenográfica.",
    "Aprender a llevar en orden las cuentas de la tienda escolar.",
    "Aprender más sobre la materia de \"Matemáticas\".",
    "Asistir a una conferencia que trate acerca de los últimos conocimientos que se tienen respecto al virus del SIDA.",
    "Excursionar en el bosque con un grupo de trabajo que explore esa región, en la búsqueda de yacimientos petroleros o mineros.",
    "Ser el orador oficial en una campaña política.",
    "Asistir a una conferencia donde se explican las causas de la formación de montañas y del subsuelo.",
    "Leer artículos acerca de los adelantos en el diseño y fabricación de motores para automóvil.",
    "Hacer colectas en la comunidad para obtener fondos cuyo fin sea mejorar las condiciones de los pobres y de los enfermos.",
    "Conocer programas computacionales para hacer cálculos y operaciones matemáticas.",
    "Ayudar en un periódico, revista o gacetilla, en la revisión de la redacción, estilo y ortografía de los artículos que publican.",
    "Trabajar durante los ratos libres en una empresa destinada a diseñar programas para organizar la información obtenida en los últimos censos poblacionales.",
    "Leer acerca de la vida y obra de los grandes músicos clásicos y modernos.",
    "Presenciar y aprender, en un laboratorio, los procedimientos o métodos de análisis que realizan los científicos (biólogos, médicos, agrónomos, bioquímicos, etc.), respecto a temas de especialidad.",
    "Visitar un museo donde haya conferencias de arte y que además exhiba pinturas, esculturas y estilos arquitectónicos de diversa índole.",
    "Trabajar en un despacho de contadores haciendo operaciones numéricas y llevando libros de contabilidad durante los ratos libres.",
    "Realizar actividades que requieren de las matemáticas.",
    "Ayudar a un grupo de presos o reos en su readaptación.",
    "Participar en un comité electoral donde se plantee la forma de organizar la información de los comicios electorales (votos).",
    "Pertenecer a un grupo de amigos cuya meta es analizar las diferentes corrientes actuales de la música y ejecutar piezas musicales.",
    "Leer artículos que hablen de los últimos hallazgos que químicos y biólogos han hecho en relación con los contaminantes del agua destinada al consumo en una gran ciudad con consecuencias en los organismos vivos en general.",
    "Asistir a un curso práctico de técnicas y uso de materiales para construcción de maquetas.",
    "Participar como jurado en un concurso de cuentos cortos.",
    "Asistir a una exposición de herramientas nuevas para la reparación y fabricación de objetos.",
    "Trabajar en un acuario con biólogos expertos, dedicados a mantener en buenas condiciones a los seres vivos que ahí se encuentran.",
    "Conocer la historia de la formación de la corteza terrestre.",
    "Ser portavoz de la sociedad de alumnos ante los directivos de la escuela.",
    "Pertenecer a un club de estudiosos dedicados a la exploración de lugares naturales como las montañas, los bosques, los desiertos y la vida campesina.",
    "Observar cómo un contador público hace cálculos de los impuestos que una empresa debe pagar al Estado.",
    "Diseñar un programa computacional para que las amas de casa, a través de un sistema sencillo, lleven el control de lo que falta en su despensa, de los pagos por hacer y de los gastos en general",
    "Participar en un programa que promueva, entre los vecinos de una colonia, mayor solidaridad y mejoras en los servicios como vigilancia, alumbrado, etcétera.",
    "Diseñar problemas numéricos para una revista de pasatiempos.",
    "Participar voluntariamente con un grupo de científicos que se dediquen a observar y dar a conocer los índices de contaminación en una gran ciudad, más las consecuencias de esto.",
    "Hacer guiones para teatro, televisión y radio.",
    "Leer artículos que hablen de la reproducción bacteriana.",
    "Organizar caminatas por las orillas de las zonas agrícolas de una región.",
    "Leer artículos acerca de las causas y consecuencias de los terremotos.",
    "Conocer e interpretar los datos presentados en la sección financiera de los noticiarios.",
    "Participar en grupos que se dedican a desarrollar técnicas y habilidades para concursar en actividades regionales, tales como discusiones, debates o polémicas.",
    "Tomar un curso relacionado con el funcionamiento e instalación de una computadora.",
    "Leer revistas que contengan reportajes acerca de diseño, decoración y uso de materiales para la construcción de piezas de ornato, técnicas de litografía, etcétera.",
    "Visitar el Conservatorio Nacional para conocer las técnicas y métodos que se emplean para enseñar la ejecución de cualquier instrumento musical.",
    "Aprender de un grupo de artesanos la forma como trabajan el latón, la piel, el vidrio, el emplomado, la decoración cerámica, etcétera.",
    "Leer revistas musicales que hablen de diferentes tipos de música.",
    "Convencer a tu grupo escolar para realizar algún proyecto o programa de actividades que tú crees importante para todos.",
    "Trabajar en una secretaría de Estado y que el desempeño de tu labor implique realizar largas caminatas por las regiones desérticas de nuestro país.",
    "Observar un documental referente a intervenciones quirúrgicas.",
    "Pertenecer a un club o sociedad cuyo fin sea analizar y compartir ideas respecto a novelas escritas en cualquier género (ficción, misterio, terror, etc.).",
    "Aprender cómo un ingeniero aplica las matemáticas a su trabajo.",
    "Conocer la manera en que el comité del censo poblacional organiza sus datos.",
    "Ver documentales televisivos que muestren los últimos hallazgos en relación con la formación del interior de la Tierra.",
    "Leer la biografía y obra de investigadores famosos.",
    "Ayudar o alentar a cualquier compañero de clase que pasa por un mal momento.",
    "Calcular los costos y las ganancias de un festival que realizarán tus compañeros.",
    "Reparar artefactos como licuadoras, tostadoras de pan, timbres, etcétera.",
    "Asistir a una conferencia referente a fósiles marinos y terrestres.",
    "Leer revistas que contengan información de los últimos avances en las ciencias de medicina, bioquímica, química y biología.",
    "Participar en campañas de concientización ciudadana.",
    "Hacer el informe financiero (ingresos y egresos) de la sociedad de alumnos.",
    "Asistir a un curso práctico ofrecido por una compañía dedicada a la fabricación de herramientas, para aprender el manejo de sus nuevas herramientas.",
    "Realizar un programa de televisión donde se hable de la historia y evolución de la música.",
    "Trabajar durante las vacaciones en una galería de arte, con algún escultor, pintor o diseñador famoso.",
    "Encargarse de la publicidad, promoción y venta de boletos para un festival estudiantil.",
    "Aprender más sobre la materia de Biología.",
    "Conocer, durante los fines de semana, lugares alejados de la ciudad, tales como establos, zonas agrícolas, poblados campesinos, regiones montañosas, etcétera.",
    "Ver películas acerca de la historia de la literatura y los literatos.",
    "Ayudar a un prestigiado maestro matemático a dar sus clases a los alumnos menos aventajados y a encontrar nuevas aplicaciones de la ciencia matemática.",
    "Observar cómo el centro de computación de una empresa organiza los datos referentes a nóminas y prestaciones a los empleados.",
    "Ayudar al bibliotecario de la escuela a diseñar un sistema con el que localicen de manera rápida a los alumnos que deben libros y que, además, ayude a encontrar libros fácilmente.",
    "Leer artículos que traten acerca de estilos arquitectónicos, de escultura y de pintura.",
    "Asistir a conciertos y conferencias de música clásica y moderna.",
    "Leer artículos que expliquen cómo funcionan los instrumentos de aeronavegación.",
    "Revisar los gastos hechos en casa durante un tiempo, con el fin de supervisar si se ha cuidado el presupuesto familiar.",
    "Fundar en tu ciudad grupos de ayuda mutua tales como Alcohólicos Anónimos o Drogadictos Anónimos.",
    "Asistir a una exposición de aparatos y máquinas electrónicas que apoyen a las ciencias médica, biológica y química, en su labor de investigación.",
    "Resolver acertijos, juegos y rompecabezas de tipo numérico.",
    "Escuchar conferencias acerca de las nuevas técnicas visuales y escritas de comunicación.",
    "Participar en campañas de reforestación, plantando árboles en las zonas boscosas del país.",
    "Leer artículos donde se explique cómo los mares erosionan la tierra.",
    "Presenciar un panel donde se hable de las epidemias y su control.",
    "Pertenecer a un club donde se dialogue, se polemicen temas de actualidad y se aprenda a hablar en público.",
    "Estudiar con algunos ecologistas las consecuencias de la sobreexplotación de las plantas.",
    "Coleccionar revistas que muestren paisajes insólitos y remotos de nuestro país.",
    "Dar clases de redacción, ortografía y técnicas de guión.",
    "Jugar con programas computacionales donde se empleen las matemáticas.",
    "Asistir a un plantel donde se hable de los últimos adelantos en metodología de la investigación en ciencias naturales.",
    "Trabajar con un grupo de geólogos que investigan yacimientos de petróleo.",
    "Ayudar a la parroquia o iglesia en la catequización y evangelización de los feligreses.",
    "Tomar un curso práctico referente a leyes fiscales (impuestos) para ayudar a un grupo de contadores.",
    "Leer escritos de la revista Mecánica popular que explican cómo reparar aparatos electrodomésticos y cómo montar aparatos electromecánicos y electrónicos.",
    "Asistir a un concierto de música moderna, ejecutado por una famosa sinfónica.",
    "Trabajar, en ratos libres, en un despacho donde se diseñen logotipos.",
    "Ser jurado en un concurso que califique el mejor sistema para organizar los expedientes de los alumnos de la preparatoria.",
    "Ser miembro de un grupo de feligreses cuyo fin sea darle ideas al párroco o ministro acerca de la forma en que puede mejorar sus sermones.",
    "Tomar un curso que hable del cuidado y conservación de las especies vivas.",
    "Ayudar a los periodistas de televisión en la redacción de las noticias.",
    "Ayudar al profesor de matemáticas a hacer los ejercicios de repaso para la clase.",
    "Ser parte de un grupo de estudiantes dedicados a diseñar las técnicas de investigación que pueda aportar datos para el cuidado de nuestro planeta.",
    "Explorar islas desiertas en el océano.",
    "Trabajar con un grupo de geólogos que se dediquen a localizar yacimientos minerales.",
    "Ver un programa de televisión dedicado a mostrar la importancia de las ciencias sociales en la vida comunitaria (psicología, derecho, educación, sociología).",
    "Conocer técnicas para convencer a la gente de que cambie de opinión.",
    "Conocer el sistema de clasificación que se emplea para ordenar los archivos de la Nación.",
    "Aprender a manejar programas de computación para diseñar, a través de la computadora, grabados, planos arquitectónicos, logotipos, etcétera.",
    "Asistir a una convención de músicos para conocer los últimos avances de la electrónica y su relación con la música.",
    "Ver una exposición de buques marinos y saber cómo están diseñados.",
    "Trabajar durante los ratos libres en una empresa que se dedique a diseñar programas de contabilidad para diferentes corporativos.",
    "Leer revistas que traten de la dinámica de los ríos subterráneos.",
    "Trabajar en una tienda comercial dedicada a la venta de CD musicales explicando a los compradores el valor musical de los diferentes géneros de música que ahí se venden.",
    "Trabajar con un grupo de escenógrafos.",
    "Hacer un programa computacional para que la mesa directiva de tu escuela pueda llevar su contabilidad, sus inventarios, etcétera.",
    "Dar un mensaje emotivo a un auditorio.",
    "Ayudar a trabajadores inmigrantes a defender sus derechos y sus intereses.",
    "Acompañar, en mar abierto, a un grupo de pescadores.",
    "Conocer cómo se aplica la computación en la investigación de las ciencias médicas, químicas y biológicas.",
    "Formar una compañía que se dedique a diseñar programas computacionales y rompecabezas numéricos.",
    "Escribir ensayos y cuentos cortos para una revista de circulación nacional.",
    "Participar como miembro en el Club de Amigos del Planeta Tierra.",
    "Asistir a conferencias en las que se hable de fenómenos tales como inflación y deuda externa.",
    "Observar cómo está diseñado el armamento pesado o artillería militar.",
  ];

  final universitarias = [
    "Resolver operaciones matemáticas.",
    "Ser asistente por temporadas de un investigador que trabaje en programas de investigación aplicada a la genética en seres vivos.",
    "Conocer los compuestos químicos de las sustancias.",
    "Hacer inventarios de lo que hay en un almacén.",
    "Ayudar a un grupo de campesinos a organizarse.",
    "Participar en un jurado que calificará un concurso teatral, en cuanto a escenografía, coreografía y guión de la obra.",
    "Trabajar en un centro dedicado a la producción de los modelos matemáticos y físicos para mejorar los productos en la industria.",
    "Participar en una operación médica.",
    "Manejar instrumentos y aparatos para elaborar productos químicos.",
    "Organizar los detalles de venta al público en un almacén.",
    "Ayudar en la rehabilitación de los presos.",
    "Diseñar la escenografía de un programa televisivo.",
    "Aplicar los principios y leyes de la física.",
    "Conocer a fondo los problemas ecológicos (ecosistema).",
    "Hacer análisis químicos del agua (su potabilidad).",
    "Determinar la relación entre inversión y utilidad de una empresa.",
    "Conocer las causas que intervienen en la desintegración familiar.",
    "Manejar con habilidad las cámaras de fotografía y de cine.",
    "Calcular fuerzas y resultantes físicas.",
    "Aplicar los principios de la cadena alimentaria entre las especies, para su conservación.",
    "Estudiar a fondo los efectos de la quimioterapia en el hombre.",
    "Determinar las funciones de los empleados en una empresa.",
    "Hacer programas para educación de los huérfanos de la casa-hogar.",
    "Conocer cómo eran nuestros antepasados a través de las pinturas, esculturas y danzas que nos legaron.",
    "Calcular matemáticamente, a través de una computadora, la probabilidad de éxito en un proyecto cualquiera.",
    "Conocer cómo funciona la reproducción bacteriana.",
    "Ser hábil para obtener nuevos compuestos químicos.",
    "Determinar los elementos sociales que estimulan los procesos económicos inflacionarios.",
    "Investigar las costumbres de vida entre las clases sociales y sus diferencias.",
    "Producir y dirigir audiovisuales, teatro y películas.",
    "Usar modelos matemáticos y físicos para realizar un trabajo.",
    "Conocer la estructura y funciones de la anatomía animal o humana.",
    "Hacer experimentos en el laboratorio de química.",
    "Llevar el inventario de productos que tiene una bodega, a través de un programa computacional.",
    "Participar en campañas de educación y concientización política.",
    "Idear nuevas técnicas de pintura, escultura y grabado.",
    "Diseñar fórmulas matemáticas y físicas, aplicables a una labor cualquiera.",
    "Conocer las causas del suicidio colectivo en algunas especies.",
    "Analizar los elementos químicos de algunas sustancias.",
    "Organizar y dirigir una empresa turística.",
    "Ayudar a una persona que pasa por momentos difíciles.",
    "Investigar por qué y para qué existe el hombre.",
    "Calcular áreas, perímetros y volumen (pueden ser calderas, hornos metalúrgicos, construcciones, etc.).",
    "Conocer las causas de la extinción de algunos organismos vivos y cómo evitarla.",
    "Determinar, mediante el análisis químico, la presencia de alguna enfermedad.",
    "Hacer las declaraciones fiscales a una pequeña cámara de comerciantes.",
    "Conocer las causas, consecuencias y soluciones del divorcio.",
    "Saber cuáles son las diferencias y semejanzas entre la música, las artesanías y las danzas características de los distintos grupos culturales.",
    "Probar nuevos programas computacionales para realizar operaciones numéricas.",
    "Conocer técnicas de mejoramiento de semillas y ganado.",
    "Manejar los productos químicos adecuados para la conservación de alimentos.",
    "Tener un despacho para asesorar empresas en el mejoramiento de su administración y organización.",
    "Participar en programas educativos que ayuden a evitar el alcoholismo y la drogadicción.",
    "Conocer la vida religiosa y artística de las tribus indígenas de nuestro país.",
    "Explicar matemática y físicamente los probables resultados de un diseño cualquiera.",
    "Conocer técnicas de siembra y recolección de frutas.",
    "Observar y conocer cómo actúan los reactivos químicos.",
    "Vigilar los rendimientos económicos de una empresa.",
    "Conocer el comportamiento humano y las causas que lo motivan.",
    "Seleccionar la música más adecuada para una película.",
    
  ];




