


List<String> Repositoriopreguntas(String inv, {String tipo = ""}) {

    switch (inv) {
      case "/inventario_autoevaluacion_aptitudes":
        return aptitudes.values.toList();
      case "/inventario_interes_ocupacional":
        return ocupacional.values.toList();
      case "/inventario_preferencias_universitarias":
        return universitarias.values.toList();
      case "/inventario_preferencias_universitarias2":
        if (tipo.isEmpty || !intereses.containsKey(tipo)) return [];
        return (intereses[tipo]["preguntas"] as Map).values.cast<String>().toList();
      default:
        return ["Tipo de lista de preguntas no válido"];
    }
}

Map <String, String> todoslosintereses() {
  Map <String, String> listainteres = {};
  for (var interesKey in intereses.keys) {
    listainteres[interesKey] = intereses[interesKey]["nombre"];
  }
  return listainteres;
}

int tamanoInventario(String inv, {String tipo = ""}) => Repositoriopreguntas(inv, tipo: tipo).length;
  final Map<String, dynamic> intereses = {
    "FM" :{
      "nombre": "Fisico Matemático",
      "rangocalificacion": 7,
      "descripcion": "",
      "carreras": [
      ],
      "preguntas":fm,
    },
    "B": {
      "nombre": "Biología",
      "rangocalificacion": 7,
      "descripcion": "Se relaciona con el interés por la naturaleza, seres vivos, salud y ciencias biológicas.",
      "carreras": [
        "Medicina",
        "Psicología",
        "Enfermería",
      ],
      "preguntas":b,
    },
    "Q": {
      "nombre": "Química",
      "rangocalificacion": 7,
      "descripcion": "Tiene que ver con experimentos, sustancias, laboratorio e investigación científica.",
      "carreras": [
        "Química",
        "QFB (Químico Farmacéutico Biólogo)",
        "Ingeniería Química",
        "Farmacia",
        "Bioquímica",
        "Toxicología",
      ],
      "preguntas":q,
    },
    "S": {
      "nombre": "Social",
      "rangocalificacion": 6,
      "descripcion": "Relacionada con ayudar a personas, comunicación y sociedad.",
      "carreras": [
        "Psicología",
        "Trabajo Social",
        "Derecho",
        "Sociología",
        "Pedagogía",
        "Ciencias de la Educación",
        "Comunicación",
      ],
      "preguntas":s,
    },
    "A": {
      "nombre": "Artística",
      "rangocalificacion": 10,
      "descripcion": "Se enfoca en creatividad, expresión y arte.",
      "carreras": [
        "Diseño Gráfico",
        "Arquitectura",
        "Artes Visuales",
        "Música",
        "Teatro",
        "Fotografía",
        "Diseño de Modas",
      ],
      "preguntas":a,
      },
    "H": {
      "nombre": "Humanística",
      "rangocalificacion": 9,
      "descripcion": "Relacionada con lectura, escritura, pensamiento crítico y cultura.",
      "carreras": [
        "Filosofía",
        "Historia",
        "Letras",
        "Periodismo",
        "Docencia",
        "Lingüística",
        "Relaciones Internacionales",
      ],
      "preguntas":h,
    },
  };
  
  final Map<int, String> aptitudes = {
    // Fila 1
    1: "Comprender con facilidad cómo se conectan algunos elementos, por ejemplo, las relaciones entre los órganos del cuerpo humano, las relaciones que se dan entre los elementos de una computadora.",
    2: "Decorar, con pincel fino, pequeñas figuras humanas (pintar la boca, ojos, cejas, etc.).",
    3: "Ayudar a un especialista en diseño de juegos electrónicos a realizar juegos entables que sean de entretenimiento numérico.",
    4: "Darte cuenta cuando un conferencista, al estar presentando su tema, lo expone de manera demasiado elemental.",
    5: "Dar buenas ideas a un grupo de vendedores (que van casa por casa) acerca de cómo convencer a los clientes para comprar el producto ofrecido.",
    6: "Aprender las partes y funciones de un velero, así como su operación y armado.",
    7: "Enseñar a alguien durante un largo período, sin interrumpirle, sin impacto, y aceptar lo como es.",
    8: "Distribuir las funciones y responsabilidades a los miembros de un grupo o equipo de trabajo, procurando que todos se sientan lo más conformes con esta distribución.",
    9: "Tomar un curso sobre comunicación no verbal en un pequeño almacén, mediante una computadora sencilla, y aprender fácilmente.",
    10: "Vencer las diferencias entre la música clásica, la popular y la moderna.",
    11: "Diseñar el logotipo de una empresa.",
    12: "Armar rompecabezas complicados (cada cubo de Rubik, por ejemplo).",
    // Fila 2
    21: "Hacer un análisis de la estructura financiera de la línea y sin ayuda de reglas.",
    13: "Reconocer tus errores cuando discutes con otra persona, aunque esto no sea de tu total agrado o tengo puntos contrarios a los tuyos.",
    15: "Diseñar una revista de pasatiempos, con problemas sencillos, con base en relaciones numéricas o químicas algebraicas.",
    16: "Explicar fácilmente, al terminar una lectura (sobre cualquier género de novelas), cómo se relacionan los personajes o cómo se desarrolla la trama.",
    20: "Idear un sistema rápido en cronista deportivo, para que gráficamente pueda organizar datos deportivos tales como: los promedios de bateo, bases robadas, home runs, etc., de una temporada.",
    19: "Ser presidente de un club social y decidir a cada uno de los miembros de la mesa directiva sus tareas y sin dudar, ser efectivos, de forma precisa.",
    14: "Aprender las partes y funciones de un planeador, así como su operación y armado.",
    18: "Inventar un método para el trabajo de publicistas sobre cómo presentar un producto en un comercial de TV o de radio.",
    17: "Entender las nomenclaturas químicas o el funcionamiento estructural de todos los órganos del cuerpo humano.",
    31: "Diseñar figuras geométricas en tres dimensiones, variando las posiciones y perspectivas.",
    23: "Ver técnicas para realizar pinturas en acuarela y óleo.",
    22: "Aprender el manejo de la herramienta propia para modelar y esculpir barro, trabajar vidrio, porcelana, latón y piel, de manera artesanal.",
    // Fila 3
    36: "Darte cuenta fácilmente si el profesor omitió un dato o punto necesario para la resolución de un problema durante el examen de matemáticas y saber con precisión lo que falta.",
    35: "Idear un sistema para pequeñas tiendas de regalos, en el que puedan llevar un inventario de la existencia de sus productos.",
    25: "Hacer un buen resumen de cualquier libro o escrito que hayas leído, con toda la información relevante bien organizada.",
    27: "Tratar por igual a todos sin distinción de clase o condición social.",
    34: "Operar y dar mantenimiento a un tractor agrícola, incluyendo sus implementos.",
    29: "Cumplir, a la perfección, una tarea asignada por tus padres, un profesor o jefe de trabajo.",
    33: "Aprender a leer, interpretar y combinar notas musicales.",
    30: "Descubrir bellamente el aparador de una tienda o un puesto de una feria o verbena.",
    26: "Reconocer en una persona que no sea de tu agrado, sus fortalezas, sus virtudes y sus aciertos.",
    47: "Comentar en un programa televisivo de la universidad, las ventajas y desventajas de las plantillas que aspiran a dirigir la sociedad de alumnos, y argumentar a favor de una de ellas.",
    24: "Sacar astillas de la piel con pinzas para las cejas (en el primer intento).",
    28: "Aprender a usar métodos científicos para profundizar en el conocimiento de las relaciones que, por ejemplo, hay entre los seres vivos que integran el ecosistema, los cambios químicos que se dan en la naturaleza, etcétera.",
    // Fila 4
    38: "Entender fácilmente el uso de un compás, y poder explicar fácilmente todas sus funciones para ver las cosas desde esa perspectiva (aunque no sea grande como punto de vista si tu compañero).",
    44: "Entender fácilmente artículos de revistas que versan sobre investigación en las ciencias naturales, como química, biología, geofísica, etcétera.",
    43: "Dar información muy completa de cualquier tema que te adhieran revisar (medidas de errores en fichas, metas que se proponen, pasos, puntos omitidos, etc.).",
    41: "Instalar, operar y darle mantenimiento a una computadora casera con sólo consultar el manual o instructivo de operaciones.",
    46: "Identificar errores ortográficos, en la organización de las párrafos y errores de redacción en cualquier escrito, aún cuando sea ilegible.",
    40: "Darle buenas sugerencias a un banco pequeño acerca de cómo organizar los departamentos de atención al público con el fin de que sus clientes no hagan largas colas de espera.",
    37: "Darte cuenta cuando un profesor comete errores al estar explicando al grupo la solución (procedimiento) de un problema de matemáticas.",
    39: "Soldar los transistores de un radio sin derramar soldadura, ni tocar con el soldador partes cercanas al transistor.",
    42: "Sugerir a alguien que va a construir su casa la forma en que debería o la distribución de la misma, aprovechando al máximo todos los espacios.",
    60: "Aprender las técnicas en el departamento de almacén comercial (libros, música, ferretería, etc.) y manejar tal vez períodos las ventas y consumo por los clientes que lo visitan.",
    32: "Aprender a ejecutar, con dominio, uno o varios instrumentos musicales.",
    45: "Recordar, detalladamente, las indicaciones dadas por alguien para llegar a una dirección desconocida.",
    // Fila 5
    51: "Aprender a diferenciar lo bello de la pintura de los grandes clásicos, en relación con otras pinturas.",
    56: "Dar a una familia consejos prácticos acerca de planear que sí compleméntente cambie ciertas actitudes de ellos.",
    55: "Comprender todo tipo y tener a tu lado, como evolucionan y se transforman los seres vivos, de acuerdo con las teorías evolucionistas de Darwin, o explicar en qué consisten las especies protegidas o seleccionamiento de tiempos químicos como lluvia.",
    53: "Fungir como tercero en un conflicto (sin tomar partido por las personas involucradas) y conciliar a las partes en pugna aunque una de ellas te simpatice mucho.",
    50: "Supervisar y corregir la redacción de un discurso que alguien competente tuvo vaya a dirigir a una asamblea.",
    58: "Aprender el sistema de clasificación que se utiliza para los archivos de la Nación.",
    52: "Dibujar a lápiz el rostro de las personas, siguiendo ciertas técnicas.",
    57: "Enseñar algunos tipos en grupos muy pequeñas, sin que lo intentes más de tres veces.",
    54: "Aplicar conocimientos matemáticos y principios de la ciencia para el diseño de puentes que no haya infringido cuando esa aplicación implique la expansión del grupo de alguien muy avanzado.",
    72: "Inventar algo útil para los aerospacios y artículos de la revista ¡Mecánica Popular!",
    49: "Recordar, durante una segunda visita, el lugar de una colonia intrincada, en donde vive alguien conocido.",
    48: "Aprender a complementar los distintos instrumentos musicales en la ejecución de una pieza.",
    // Fila 6
    70: "Aprender técnicas para construir maquetas y objetos de cualquier tipo a escala. (Por ejemplo, un avión, un ayuda de campo con material).",
    65: "Entender fácilmente la explicación de un armero sobre cómo funciona cierto tipo de armamento militar, ya sea fusiles, ametralladoras o artillería en miniatura.",
    66: "Prever e identificar las consecuencias para ti y para los demás (de manera detallada y precisa) de las decisiones que tomes.",
    68: "Colocar sin errores, con pinzas pequeñas, los engranes de un reloj.",
    71: "Explicar los factores por el material a un grupo de compañeros menos aventajados, de manera más sencilla que el profesor.",
    63: "Aprender y manejar el sistema de clasificación y localización de piezas en una refaccionaria de automóviles.",
    69: "Explicar de forma clara y lógica a un grupo de personas, con las mismas palabras y con ejemplos ilustrativos, el manejo de algún aparato técnico que tú ya domines.",
    64: "Comprender con facilidad cómo una persona cercana a ti ve desde su interior el mundo. Comprender también los sentimientos que tiene y sus expectativas.",
    67: "Aplicar las leyes y teorías de la química o de la biología cuando resolvemos un problema de matemáticas.",
    83: "Generar argumentos, ante un auditorio, a favor de tu punto de vista o de algún proyecto.",
    61: "Aprender a hacer arreglos musicales.",
    59: "Resolver problemas de matemáticas y seleccionar las fórmulas y procedimientos necesarios de manera precisa y fácil.",
    // Fila 7
    78: "Apretar, con un pequeño desarmador, los tornillos de los anteojos.",
    74: "Dar una conferencia sobre un tema de computación tuya tonga éxito en una campaña política o en cualquier actividad.",
    73: "Aprender con facilidad a afinar automóviles o a dar mantenimiento y reparación a aparatos caseros como: podadoras de pasto, calentadores de gas, estufas, etcétera.",
    80: "Dar ideas al párroco o ministro de tu iglesia acerca de cómo mejorar sus sermones o sus actividades espirituales.",
    77: "Obtener fácilmente conclusiones a una síntesis de algún trabajo que hayas encargado el profesor de biología o de química sobre cualquier tema.",
    76: "Darte cuenta de los deseos, preocupaciones o sentimientos de alguien, solo por ver sus gestos y movimientos.",
    79: "Estudiar e interpretar las instrucciones y las preguntas de un examen.",
    75: "Diseñarle a una pequeña ferretería un sistema para localizar rápidamente los productos que el cliente pide.",
    81: "Combinar materiales de todo tipo (yeso, madera, pinturas) para hacer objetos de ornato, como floreros, ceniceros, pisapapeles, etcétera.",
    105: "Armar aparatos de radio, televisión, amplificadores, grabadoras, etcétera.",
    82: "Aprender con facilidad a escribir y arreglar canciones y composiciones musicales.",
    62: "Distinguir errores en las perspectivas de los dibujos.",
    // Fila 8
    93: "Hacerle ver a un grupo que discute cosas que no han considerado o puntos omitidos que pueden influir en sus opiniones sobre lo discutido.",
    88: "Construir, en un taller de aficionados, artefactos sencillos como un velero, un planeador, etcétera.",
    89: "Lograr entusiasmar a un grupo de trabajo que se encuentra pesimista en cuanto a las metas de trabajo por lograr.",
    91: "Enhebrarse rápidamente un collar de perlas.",
    85: "Darte cuenta de inmediato de cuál es el error de un compañero que no puede resolver correctamente un problema de matemáticas.",
    86: "Participar con un diseño tuyo, con probabilidades de ganar, en un concurso de la escuela cuyo objetivo o meta sea el de proponer un sistema de clasificación para los expedientes de los estudiantes.",
    92: "Darte cuenta de inmediato cuando un profesor se aplica un examen con errores de contenido o en la clasificación de las preguntas.",
    87: "Predecir la forma en que un conocido tuyo va a actuar, lo que va a decir y a pensar en una situación dada.",
    90: "Comprender la relación entre estructuras y funciones de los órganos del cuerpo humano; establecer cómo se relacionan todos los sistemas, o hacer esto mismo con plantas o animales.",
    109: "Diseñar la decoración de un hogar o una oficina.",
    94: "Hacerle a un carpintero, detalladamente (con ángulos, medidas, superficies, etc.), un diseño sobre el tipo de muebles que necesitas hacer.",
    84: "Entender los principios (cómo funcionan las hipótesis, como relacionaciones, como componentes, instrumentos, cómo operan, etcétera) de todo lo que un químico o algún biólogo famoso logra llegar a sus descubrimientos.",
    // Fila 9
    96: "Darte cuenta rápidamente cuando alguien está pasando por un mal momento y necesita de tu ayuda sin que te lo pida.",
    101: "Escribir sin galón teatral o alguna pequeña obra, relacionando y ordenando correctamente los diálogos de los personajes, las escenas, etcétera.",
    100: "Mejorar el procedimiento de inscripciones en la escuela, creando uno más rápido, más fácil, práctico y eficiente.",
    98: "Prestar ayuda al profesor de matemáticas para plantear problemas de repaso referentes a toda la materia.",
    104: "Pegar piedras preciosas en un collar, viendo a través de una lupa.",
    103: "Hacer que todos los miembros de un grupo de trabajo que tienes, sin sentirse presionado o perseguido.",
    97: "Ayudarte fácilmente a que un curso la reparación de productos electrónicos, mecánicos, etc., y que te quede fundamenta.",
    102: "Aprender a ser un buen orador mediante un curso rápido y sencillo.",
    99: "Darte cuenta cuando alguien tiene un error en la ejecución de una pieza musical.",
    113: "Dibujar figuras en detalles complicadas, con instrumentos, etc.) de las.",
    106: "Ejemplificar fácilmente cómo se pueden observar en la vida cotidiana las leyes y principios de la biología o de la química.",
    95: "Saber identificar el momento oportuno para dar un consejo, empezar una conversación, o hacer una pregunta a alguien con quien no se puede platicar muy fácilmente.",
    // Fila 10
    107: "Dirigir un grupo musical que interprete melodías de moda.",
    114: "Hacer fácil y rápidamente composición escritas, unas oraciones, párrafos, títulos o subtítulos, según todas las desedan.",
    112: "Aprender como computar las datos (nóminas, inventarios, egresos, ingresos, etc.), de un pequeño comercio.",
    110: "Diseñar putos de examen con problemas y ejercicios de matemáticas para la clase.",
    117: "Interpretar muy bien al sello de la música que más te gusta, tocas.",
    116: "Armar y desarraigar rapidamente y sin errores un reloj de pulso.",
    108: "Identificar las limitantes físicas de los miembros de un grupo de trabajo para asignarles responsabilidades en una tarea determinada.",
    115: "Entender fácilmente la aplicación de un aparato no eléctrico para soltar molino sobre la forma en que se combina la electrónica, la electricidad y la mecánica, en la construcción del armamento de la aviación.",
    111: "Preparar y dar un discurso a un auditorio acerca de la necesidad de cuidar la Tierra de forma que los futuros generados no se vean en el descuido de deterioro ambiental, o acerca de tomar las medidas necesarias.",
    118: "Recortar con facilidad el ritmo de las piezas musicales que más te agradan.",
    120: "Reducir con facilidad los lugares de un estacionamiento de coches en forma tal que quepan más autos en la capa y finales cada espacio.",
    119: "Decorar objetos cerámicos, de piel, de madera, de barro, etcétera."
  };


  final Map<int, String> ocupacional = {
    // Fila 1
    2: "Ser comentarista de temas diversos en un programa de televisión.",
    3: "Leer una revista en donde se explique cómo se relacionan los seres vivos en el ecosistema.",
    4: "Coleccionar revistas como las de Mecánica popular y Ármelo usted mismo.",
    5: "Vivir temporadas largas en las rancherías y en las labores o cultivos para realizar trabajos diversos.",
    6: "Visitar una exposición donde se exhiben residuos de meteoritos o rocas de todo tipo provenientes del espacio, de grutas famosas, del fondo del océano, etcétera.",
    7: "Participar en campañas cuyo fin es concientizar a la población marginada de la necesidad de organizarse para crear cooperativas de consumo.",
    8: "Leer biografías u obras de literatos famosos.",
    1: "Observar en una biblioteca cómo clasifican sus libros, y conocer el sistema de clasificación.",
    13: "Participar en un grupo musical dedicado a rescatar e interpretar música no comercial.",
    12: "Colaborar con el grupo de \"Amigos de la Tierra\" (biólogos, químicos, bioquímicos, médicos, etc.), en la recolección de datos estadísticos que demuestren la necesidad de cuidar nuestro mundo.",
    9: "Ser parte de un jurado que califique, en un concurso, la mejor composición escenográfica.",
    11: "Aprender a llevar en orden las cuentas de la tienda escolar.",
    10: "Aprender más sobre la materia de \"Matemáticas\".",
    // Fila 2
    14: "Asistir a una conferencia que trate acerca de los últimos conocimientos que se tienen respecto al virus del SIDA.",
    18: "Excursionar en el bosque con un grupo de trabajo que explore esa región, en la búsqueda de yacimientos petroleros o mineros.",
    15: "Ser el orador oficial en una campaña política.",
    17: "Asistir a una conferencia donde se explican las causas de la formación de montañas y del subsuelo.",
    19: "Leer artículos acerca de los adelantos en el diseño y fabricación de motores para automóvil.",
    21: "Hacer colectas en la comunidad para obtener fondos cuyo fin sea mejorar las condiciones de los pobres y de los enfermos.",
    22: "Conocer programas computacionales para hacer cálculos y operaciones matemáticas.",
    16: "Ayudar en un periódico, revista o gacetilla, en la revisión de la redacción, estilo y ortografía de los artículos que publican.",
    20: "Trabajar durante los ratos libres en una empresa destinada a diseñar programas para organizar la información obtenida en los últimos censos poblacionales.",
    26: "Leer acerca de la vida y obra de los grandes músicos clásicos y modernos.",
    23: "Presenciar y aprender, en un laboratorio, los procedimientos o métodos de análisis que realizan los científicos (biólogos, médicos, agrónomos, bioquímicos, etc.), respecto a temas de especialidad.",
    25: "Visitar un museo donde haya conferencias de arte y que además exhiba pinturas, esculturas y estilos arquitectónicos de diversa índole.",
    24: "Trabajar en un despacho de contadores haciendo operaciones numéricas y llevando libros de contabilidad durante los ratos libres.",
    // Fila 3
    35: "Realizar actividades que requieren de las matemáticas.",
    34: "Ayudar a un grupo de presos o reos en su readaptación.",
    38: "Participar en un comité electoral donde se plantee la forma de organizar la información de los comicios electorales (votos).",
    36: "Pertenecer a un grupo de amigos cuya meta es analizar las diferentes corrientes actuales de la música y ejecutar piezas musicales.",
    28: "Leer artículos que hablen de los últimos hallazgos que químicos y biólogos han hecho en relación con los contaminantes del agua destinada al consumo en una gran ciudad con consecuencias en los organismos vivos en general.",
    33: "Asistir a un curso práctico de técnicas y uso de materiales para construcción de maquetas.",
    29: "Participar como jurado en un concurso de cuentos cortos.",
    37: "Asistir a una exposición de herramientas nuevas para la reparación y fabricación de objetos.",
    27: "Trabajar en un acuario con biólogos expertos, dedicados a mantener en buenas condiciones a los seres vivos que ahí se encuentran.",
    39: "Conocer la historia de la formación de la corteza terrestre.",
    30: "Ser portavoz de la sociedad de alumnos ante los directivos de la escuela.",
    32: "Pertenecer a un club de estudiosos dedicados a la exploración de lugares naturales como las montañas, los bosques, los desiertos y la vida campesina.",
    31: "Observar cómo un contador público hace cálculos de los impuestos que una empresa debe pagar al Estado.",
    // Fila 4
    45: "Diseñar un programa computacional para que las amas de casa, a través de un sistema sencillo, lleven el control de lo que falta en su despensa, de los pagos por hacer y de los gastos en general",
    50: "Participar en un programa que promueva, entre los vecinos de una colonia, mayor solidaridad y mejoras en los servicios como vigilancia, alumbrado, etcétera.",
    46: "Diseñar problemas numéricos para una revista de pasatiempos.",
    47: "Participar voluntariamente con un grupo de científicos que se dediquen a observar y dar a conocer los índices de contaminación en una gran ciudad, más las consecuencias de esto.",
    41: "Hacer guiones para teatro, televisión y radio.",
    44: "Leer artículos que hablen de la reproducción bacteriana.",
    40: "Organizar caminatas por las orillas de las zonas agrícolas de una región.",
    49: "Leer artículos acerca de las causas y consecuencias de los terremotos.",
    42: "Conocer e interpretar los datos presentados en la sección financiera de los noticiarios.",
    48: "Participar en grupos que se dedican a desarrollar técnicas y habilidades para concursar en actividades regionales, tales como discusiones, debates o polémicas.",
    52: "Tomar un curso relacionado con el funcionamiento e instalación de una computadora.",
    51: "Leer revistas que contengan reportajes acerca de diseño, decoración y uso de materiales para la construcción de piezas de ornato, técnicas de litografía, etcétera.",
    43: "Visitar el Conservatorio Nacional para conocer las técnicas y métodos que se emplean para enseñar la ejecución de cualquier instrumento musical.",
    // Fila 5
    57: "Aprender de un grupo de artesanos la forma como trabajan el latón, la piel, el vidrio, el emplomado, la decoración cerámica, etcétera.",
    65: "Leer revistas musicales que hablen de diferentes tipos de música.",
    56: "Convencer a tu grupo escolar para realizar algún proyecto o programa de actividades que tú crees importante para todos.",
    61: "Trabajar en una secretaría de Estado y que el desempeño de tu labor implique realizar largas caminatas por las regiones desérticas de nuestro país.",
    63: "Observar un documental referente a intervenciones quirúrgicas.",
    58: "Pertenecer a un club o sociedad cuyo fin sea analizar y compartir ideas respecto a novelas escritas en cualquier género (ficción, misterio, terror, etc.).",
    60: "Aprender cómo un ingeniero aplica las matemáticas a su trabajo.",
    55: "Conocer la manera en que el comité del censo poblacional organiza sus datos.",
    59: "Ver documentales televisivos que muestren los últimos hallazgos en relación con la formación del interior de la Tierra.",
    64: "Leer la biografía y obra de investigadores famosos.",
    54: "Ayudar o alentar a cualquier compañero de clase que pasa por un mal momento.",
    53: "Calcular los costos y las ganancias de un festival que realizarán tus compañeros.",
    62: "Reparar artefactos como licuadoras, tostadoras de pan, timbres, etcétera.",
    // Fila 6
    74: "Asistir a una conferencia referente a fósiles marinos y terrestres.",
    70: "Leer revistas que contengan información de los últimos avances en las ciencias de medicina, bioquímica, química y biología.",
    75: "Participar en campañas de concientización ciudadana.",
    66: "Hacer el informe financiero (ingresos y egresos) de la sociedad de alumnos.",
    68: "Asistir a un curso práctico ofrecido por una compañía dedicada a la fabricación de herramientas, para aprender el manejo de sus nuevas herramientas.",
    76: "Realizar un programa de televisión donde se hable de la historia y evolución de la música.",
    78: "Trabajar durante las vacaciones en una galería de arte, con algún escultor, pintor o diseñador famoso.",
    73: "Encargarse de la publicidad, promoción y venta de boletos para un festival estudiantil.",
    77: "Aprender más sobre la materia de Biología.",
    69: "Conocer, durante los fines de semana, lugares alejados de la ciudad, tales como establos, zonas agrícolas, poblados campesinos, regiones montañosas, etcétera.",
    71: "Ver películas acerca de la historia de la literatura y los literatos.",
    72: "Ayudar a un prestigiado maestro matemático a dar sus clases a los alumnos menos aventajados y a encontrar nuevas aplicaciones de la ciencia matemática.",
    67: "Observar cómo el centro de computación de una empresa organiza los datos referentes a nóminas y prestaciones a los empleados.",
    // Fila 7
    90: "Ayudar al bibliotecario de la escuela a diseñar un sistema con el que localicen de manera rápida a los alumnos que deben libros y que, además, ayude a encontrar libros fácilmente.",
    82: "Leer artículos que traten acerca de estilos arquitectónicos, de escultura y de pintura.",
    88: "Asistir a conciertos y conferencias de música clásica y moderna.",
    89: "Leer artículos que expliquen cómo funcionan los instrumentos de aeronavegación.",
    84: "Revisar los gastos hechos en casa durante un tiempo, con el fin de supervisar si se ha cuidado el presupuesto familiar.",
    87: "Fundar en tu ciudad grupos de ayuda mutua tales como Alcohólicos Anónimos o Drogadictos Anónimos.",
    79: "Asistir a una exposición de aparatos y máquinas electrónicas que apoyen a las ciencias médica, biológica y química, en su labor de investigación.",
    91: "Resolver acertijos, juegos y rompecabezas de tipo numérico.",
    86: "Escuchar conferencias acerca de las nuevas técnicas visuales y escritas de comunicación.",
    83: "Participar en campañas de reforestación, plantando árboles en las zonas boscosas del país.",
    81: "Leer artículos donde se explique cómo los mares erosionan la tierra.",
    80: "Presenciar un panel donde se hable de las epidemias y su control.",
    85: "Pertenecer a un club donde se dialogue, se polemicen temas de actualidad y se aprenda a hablar en público.",
    // Fila 8
    92: "Estudiar con algunos ecologistas las consecuencias de la sobreexplotación de las plantas.",
    100: "Coleccionar revistas que muestren paisajes insólitos y remotos de nuestro país.",
    93: "Dar clases de redacción, ortografía y técnicas de guión.",
    97: "Jugar con programas computacionales donde se empleen las matemáticas.",
    98: "Asistir a un plantel donde se hable de los últimos adelantos en metodología de la investigación en ciencias naturales.",
    94: "Trabajar con un grupo de geólogos que investigan yacimientos de petróleo.",
    103: "Ayudar a la parroquia o iglesia en la catequización y evangelización de los feligreses.",
    104: "Tomar un curso práctico referente a leyes fiscales (impuestos) para ayudar a un grupo de contadores.",
    95: "Leer escritos de la revista Mecánica popular que explican cómo reparar aparatos electrodomésticos y cómo montar aparatos electromecánicos y electrónicos.",
    99: "Asistir a un concierto de música moderna, ejecutado por una famosa sinfónica.",
    101: "Trabajar, en ratos libres, en un despacho donde se diseñen logotipos.",
    102: "Ser jurado en un concurso que califique el mejor sistema para organizar los expedientes de los alumnos de la preparatoria.",
    96: "Ser miembro de un grupo de feligreses cuyo fin sea darle ideas al párroco o ministro acerca de la forma en que puede mejorar sus sermones.",
    // Fila 9
    105: "Tomar un curso que hable del cuidado y conservación de las especies vivas.",
    116: "Ayudar a los periodistas de televisión en la redacción de las noticias.",
    109: "Ayudar al profesor de matemáticas a hacer los ejercicios de repaso para la clase.",
    110: "Ser parte de un grupo de estudiantes dedicados a diseñar las técnicas de investigación que pueda aportar datos para el cuidado de nuestro planeta.",
    111: "Explorar islas desiertas en el océano.",
    106: "Trabajar con un grupo de geólogos que se dediquen a localizar yacimientos minerales.",
    113: "Ver un programa de televisión dedicado a mostrar la importancia de las ciencias sociales en la vida comunitaria (psicología, derecho, educación, sociología).",
    112: "Conocer técnicas para convencer a la gente de que cambie de opinión.",
    107: "Conocer el sistema de clasificación que se emplea para ordenar los archivos de la Nación.",
    117: "Aprender a manejar programas de computación para diseñar, a través de la computadora, grabados, planos arquitectónicos, logotipos, etcétera.",
    115: "Asistir a una convención de músicos para conocer los últimos avances de la electrónica y su relación con la música.",
    114: "Ver una exposición de buques marinos y saber cómo están diseñados.",
    108: "Trabajar durante los ratos libres en una empresa que se dedique a diseñar programas de contabilidad para diferentes corporativos.",
    // Fila 10
    128: "Leer revistas que traten de la dinámica de los ríos subterráneos.",
    130: "Trabajar en una tienda comercial dedicada a la venta de CD musicales explicando a los compradores el valor musical de los diferentes géneros de música que ahí se venden.",
    124: "Trabajar con un grupo de escenógrafos.",
    118: "Hacer un programa computacional para que la mesa directiva de tu escuela pueda llevar su contabilidad, sus inventarios, etcétera.",
    123: "Dar un mensaje emotivo a un auditorio.",
    127: "Ayudar a trabajadores inmigrantes a defender sus derechos y sus intereses.",
    121: "Acompañar, en mar abierto, a un grupo de pescadores.",
    122: "Conocer cómo se aplica la computación en la investigación de las ciencias médicas, químicas y biológicas.",
    126: "Formar una compañía que se dedique a diseñar programas computacionales y rompecabezas numéricos.",
    129: "Escribir ensayos y cuentos cortos para una revista de circulación nacional.",
    119: "Participar como miembro en el Club de Amigos del Planeta Tierra.",
    120: "Asistir a conferencias en las que se hable de fenómenos tales como inflación y deuda externa.",
    125: "Observar cómo está diseñado el armamento pesado o artillería militar.",
  };

  final universitarias = {
    // Fila 1
    1:"Resolver operaciones matemáticas.",
    2:"Ser asistente por temporadas de un investigador que trabaje en programas de investigación aplicada a la genética en seres vivos.",
    3:"Conocer los compuestos químicos de las sustancias.",
    4:"Hacer inventarios de lo que hay en un almacén.",
    5:"Ayudar a un grupo de campesinos a organizarse.",
    6:"Participar en un jurado que calificará un concurso teatral, en cuanto a escenografía, coreografía y guión de la obra.",
   // Fila 2
    7:"Trabajar en un centro dedicado a la producción de los modelos matemáticos y físicos para mejorar los productos en la industria.",
    8:"Participar en una operación médica.",
    9:"Manejar instrumentos y aparatos para elaborar productos químicos.",
    10:"Organizar los detalles de venta al público en un almacén.",
    11:"Ayudar en la rehabilitación de los presos.",
    12:"Diseñar la escenografía de un programa televisivo.",
    // Fila 3
    13:"Aplicar los principios y leyes de la física.",
    14:"Conocer a fondo los problemas ecológicos (ecosistema).",
    15:"Hacer análisis químicos del agua (su potabilidad).",
    16:"Determinar la relación entre inversión y utilidad de una empresa.",
    17:"Conocer las causas que intervienen en la desintegración familiar.",
    18:"Manejar con habilidad las cámaras de fotografía y de cine.",
    // Fila 4
    19:"Calcular fuerzas y resultantes físicas.",
    20:"Aplicar los principios de la cadena alimentaria entre las especies, para su conservación.",
    21:"Estudiar a fondo los efectos de la quimioterapia en el hombre.",
    22:"Determinar las funciones de los empleados en una empresa.",
    23:"Hacer programas para educación de los huérfanos de la casa-hogar.",
    24:"Conocer cómo eran nuestros antepasados a través de las pinturas, esculturas y danzas que nos legaron.",
    // Fila 5
    25:"Calcular matemáticamente, a través de una computadora, la probabilidad de éxito en un proyecto cualquiera.",
    26:"Conocer cómo funciona la reproducción bacteriana.",
    27:"Ser hábil para obtener nuevos compuestos químicos.",
    28:"Determinar los elementos sociales que estimulan los procesos económicos inflacionarios.",
    29:"Investigar las costumbres de vida entre las clases sociales y sus diferencias.",
    30:"Producir y dirigir audiovisuales, teatro y películas.",
    // Fila 6
    31:"Usar modelos matemáticos y físicos para realizar un trabajo.",
    32:"Conocer la estructura y funciones de la anatomía animal o humana.",
    33:"Hacer experimentos en el laboratorio de química.",
    34:"Llevar el inventario de productos que tiene una bodega, a través de un programa computacional.",
    35:"Participar en campañas de educación y concientización política.",
    36:"Idear nuevas técnicas de pintura, escultura y grabado.",
    // Fila 7
    37:"Diseñar fórmulas matemáticas y físicas, aplicables a una labor cualquiera.",
    38:"Conocer las causas del suicidio colectivo en algunas especies.",
    39:"Analizar los elementos químicos de algunas sustancias.",
    40:"Organizar y dirigir una empresa turística.",
    41:"Ayudar a una persona que pasa por momentos difíciles.",
    42:"Investigar por qué y para qué existe el hombre.",
    // Fila 8
    43:"Calcular áreas, perímetros y volumen (pueden ser calderas, hornos metalúrgicos, construcciones, etc.).",
    44:"Conocer las causas de la extinción de algunos organismos vivos y cómo evitarla.",
    45:"Determinar, mediante el análisis químico, la presencia de alguna enfermedad.",
    46:"Hacer las declaraciones fiscales a una pequeña cámara de comerciantes.",
    47:"Conocer las causas, consecuencias y soluciones del divorcio.",
    48:"Saber cuáles son las diferencias y semejanzas entre la música, las artesanías y las danzas características de los distintos grupos culturales.",
    // Fila 9
    49:"Probar nuevos programas computacionales para realizar operaciones numéricas.",
    50:"Conocer técnicas de mejoramiento de semillas y ganado.",
    51:"Manejar los productos químicos adecuados para la conservación de alimentos.",
    52:"Tener un despacho para asesorar empresas en el mejoramiento de su administración y organización.",
    53:"Participar en programas educativos que ayuden a evitar el alcoholismo y la drogadicción.",
    54:"Conocer la vida religiosa y artística de las tribus indígenas de nuestro país.",
    // Fila 10
    55:"Explicar matemática y físicamente los probables resultados de un diseño cualquiera.",
    56:"Conocer técnicas de siembra y recolección de frutas.",
    57:"Observar y conocer cómo actúan los reactivos químicos.",
    58:"Vigilar los rendimientos económicos de una empresa.",
    59:"Conocer el comportamiento humano y las causas que lo motivan.",
    60:"Seleccionar la música más adecuada para una película.",
  }
  ;

  final fm = {
    1: "Descubrir nuevas fórmulas matemáticas.",
    2: "Aplicar las teorías de la física al diseño de motores eléctricos.",
    3: "Deducir, por medio de los principios físicos y el cálculo, el lugar donde pudiera existir un manto acuífero, en el subsuelo.",
    4: "Diseñar un sistema para controlar la calidad de los productos en una empresa.",
    5: "Calcular la estructura de un edificio, para su construcción.",
    6: "Hacer las estadísticas de accidentes, para una compañía de seguros.",
    7: "Asesorar a compañías constructoras en la determinación de colindancias y áreas de terreno donde se construirá un fraccionamiento.",
    8: "Trabajar para una industria automotriz, en el diseño de carrocerías para automóviles y de los interiores del mismo.",
    9: "Buscar nuevas formas numéricas que permitan explicar y predecir algunos fenómenos físicos.",
    10: "Conocer el sistema interno de una computadora.",
    11: "Explorar en el campo abierto las posibilidades de existencia de un manto petrolero o minero.",
    12: "Organizar una empresa rural para que su proceso industrial de manufactura sea más eficiente.",
    13: "Supervisar la construcción de carreteras y puentes.",
    14: "Hacer estudios estadísticos para el Gobierno federal en cuanto a la proporción de tráfico en una carretera.",
    15: "Hacer estudios para una compañía constructora que se encarga de construir una nueva línea ferroviaria y de determinar los niveles o alturas a los que tendrá que condicionarse esta obra.",
    16: "Diseñar en una empresa mueblera los sillones y sillas que lanzará al mercado.",
    17: "Profundizar en las teorías de la relatividad de Albert Einstein.",
    18: "Conocer el funcionamiento de los instrumentos de aeronavegación.",
    19: "Saber cuál es la composición de las rocas y de las capas geofísicas.",
    20: "Conocer con detalle cómo se relacionan los diferentes departamentos de una empresa.",
    21: "Diseñar casas habitación.",
    22: "Asesorar a la Comisión Nacional de Censos Poblacionales en campañas acerca de cómo llevar e interpretar la estadística de la información obtenida.",
    23: "Hacer estudios para el Gobierno federal respecto a la probabilidad de construir canales de riego que puedan conducir el agua, con base en el cálculo de la fuerza de gravedad.",
    24: "Trabajar en una empresa que fabrica novedades en la línea de regalos y diseñar nuevos modelos de productos (cajas musicales, bolsas de mano, etc.).",
    25: "Conocer a fondo la lógica de las matemáticas.",
    26: "Conocer y reparar los instrumentos electrónicos de un hospital.",
    27: "Explicar el porqué de la formación de las montañas y los terrenos.",
    28: "Diseñar el orden en que deben operar los diferentes departamentos de una nueva empresa manufacturera.",
    29: "Remodelar construcciones antiguas.",
    30: "Asesorar a una compañía de seguros para determinar los costos de los mismos, con base en la probabilidad de accidentes.",
    31: "Medir grandes extensiones de terreno para realizar una división exacta del mismo.",
    32: "Trabajar en el departamento de diseño para muebles de baño en una empresa fabricante de porcelanas.",
    33: "Conocer a fondo la relación entre álgebra y geometría.",
    34: "Conocer a fondo el funcionamiento de los sistemas eléctricos.",
    35: "Conocer y explicar la historia y evolución de la geografía marina.",
    36: "Supervisar y analizar las funciones de los diversos departamentos en una industria.",
    37: "Embellecer las construcciones de un centro turístico.",
    38: "Diseñarle un modelo matemático a una industria con el fin de que mejore la calidad de sus productos.",
    39: "Medir alturas de terrenos y montañas con objeto de elaborar cartas geográficas.",
    40: "Asesorar a una compañía constructora de carrocerías para remolques en el diseño de los mismos.",
    41: "Lograr nuevas aplicaciones de matemáticas a problemas de física.",
    42: "Calcular la resistencia y duración de un motor, bajo condiciones experimentales.",
    43: "Conocer el porqué de la formación de los diferentes fósiles marinos y terrestres.",
    44: "Diseñar la empresa del futuro.",
    45: "Diseñar zonas urbanas más habitables y dignas, a menor costo.",
    46: "Trabajar en un departamento universitario que reúna información acerca de los alumnos y aportar ideas de cómo organizar estadísticamente los datos.",
    47: "Hacer cálculos para una compañía minera respecto a los niveles de profundidad de sus excavaciones, con el fin de evitarles inundaciones.",
    48: "Aprender técnicas para el diseño y dibujo de piezas mecánicas o de cualquier tipo.",
    49: "Buscar nuevas relaciones entre el cálculo y la geometría.",
    50: "Conocer cómo funcionan los medios de comunicación electrónicos (televisión por satélite, teléfonos, etc.).",
    51: "Saber detectar posibles vetas de minerales.",
    52: "Encontrar nuevos sistemas para manufacturar productos en forma tal que, por su costo, puedan ser más accesibles al público.",
    53: "Calcular y diseñar lozas, columnas y cimientos para una construcción.",
    54: "Diseñar un modelo matemático y estadístico para una gran cadena de supermercados, con el fin de predecir el éxito que tendría con sus clientes al inaugurar una nueva tienda.",
    55: "Hacer estudios topológicos para ayudar a los agricultores a nivelar bien sus terrenos de riego.",
    56: "Aplicar el dibujo y la geometría para el diseño de nuevos modelos en muebles de cocina en general.",
    57: "Profundizar en el estudio de la física y de las matemáticas.",
    58: "Conocer cómo funcionan y se manejan los instrumentos de navegación marina.",
    59: "Conocer cómo están constituidas las capas del subsuelo.",
    60: "Saber cómo deben estar distribuidos y relacionados los departamentos en una maquila que elabora ropa.",
    61: "Conocer en detalle la historia de la construcción y los estilos arquitectónicos.",
    62: "Asesorar a un departamento del Estado acerca de cómo llevar la estadística nacional de mortalidad.",
    63: "Determinar, por medio del cálculo, la altura sobre el nivel del mar de algunas regiones.",
    64: "Conocer las técnicas del diseño y modelado que permitan hacer piezas para reproducirlas en serie.",
    65: "Investigar de qué manera se podría aplicar la física y las matemáticas a las ciencias en general.",
    66: "Saber en detalle cómo está diseñado un avión, además de conocer los principios físicos que lo rigen.",
    67: "Saber cómo pronosticar el clima y los fenómenos meteorológicos en general.",
    68: "Diseñar dentro de una empresa comercial el procedimiento de compra y venta, de forma tal que el cliente y la empresa estén siempre contentos.",
    69: "Conocer las propiedades de los materiales de construcción (cemento, varilla, etc.).",
    70: "Asesorar a un grupo de directivos de una compañía de seguros en cuanto a cómo recabar datos estadísticos de siniestros.",
    71: "Asesorar al municipio en la medición de colindancias de los terrenos urbanos para actualizar el catastro.",
    72: "Trabajar en una empresa o industria que fabrique productos, como carritos tubulares de supermercados, y mejorar los diseños de los mismos.",
    73: "Dedicarse de por vida a investigar nuevas fórmulas matemáticas, físicas, etcétera.",
    74: "Conocer a fondo el funcionamiento de relojes, radios, motores, etcétera.",
    75: "Diseñar sistemas de extracción para los minerales del subsuelo.",
    76: "Asesorar a empresas para mejorar el proceso de manufactura en los productos que generan.",
    77: "Crear construcciones con un estilo arquitectónico donde la gente que las habite disfrute de algo insólito y experimente bienestar.",
    78: "Aplicar la matemática en la resolución de problemas sociales.",
    79: "Diseñar cartas marítimas donde los tripulantes de navíos puedan observar las elevaciones exactas de los terrenos bajo el mar.",
    80: "Trabajar en un centro de diseño que asesore a empresas en la actualización de modelos de mobiliarios para oficina, modelos nuevos de motocicletas, de bicicletas, etcétera.",
  };

  final Map<int, String> b = {
    1: "Conocer profundamente la relación entre los organismos de la cadena alimentaria.",
    2: "Participar en una intervención quirúrgica.",
    3: "Conocer y controlar las epidemias que afectan a las aves.",
    4: "Saber cómo aplicar las técnicas de rotación de cultivos.",
    5: "Trabajar en una región boscosa del país, en la reforestación de donde han sido talados los árboles.",
    6: "Diseñar para el gobierno municipal mejores formas de recolección y uso de la basura.",
    7: "Estudiar a fondo las relaciones entre los organismos marinos y el medio en que viven.",
    8: "Conocer con detalle la vida de los insectos y de los microorganismos.",
    9: "Conocer la anatomía humana, su estructura y su función.",
    10: "Saber vacunar al ganado para prevenir sus enfermedades.",
    11: "Conocer la tecnología de preparación de tierra para el cultivo.",
    12: "Conocer con detalle las teorías existentes respecto a la vida y función de árboles de todo tipo: frutales, coníferas, maderas preciosas, etcétera.",
    13: "Realizar estudios del uso racional del agua y su conservación en una ciudad.",
    14: "Conocer técnicas para cultivar artificialmente algunos tipos de peces.",
    15: "Investigar las consecuencias que acarrearía el desbalance del ecosistema.",
    16: "Conocer los nutrimentos más adecuados para el organismo humano.",
    17: "Participar en la operación o intervención quirúrgica de caballos, vacas, etcétera.",
    18: "Conocer las enfermedades típicas de las hortalizas, sus remedios y su técnica de siembra.",
    19: "Trabajar en un aserradero supervisando el corte racional de árboles.",
    20: "Realizar investigaciones encaminadas a mejorar el ecosistema.",
    21: "Conocer con detalle el comportamiento de los peces, para utilizarlo en las técnicas para su captura.",
    22: "Profundizar en las teorías darwinianas acerca de la evolución de las especies.",
    23: "Saber las técnicas de odontología para intervenciones bucales.",
    24: "Conocer y tratar las enfermedades más comunes del ganado vacuno.",
    25: "Trabajar en algún huerto productor de cítricos controlando sus plagas, sus enfermedades, y conocer las técnicas de siembra y de reproducción de los mismos.",
    26: "Diseñar programas para la siembra de árboles, de manera científica y organizada.",
    27: "Asesorar al gobierno de un estado para el correcto manejo de desechos industriales con visos a evitar la destrucción del ambiente.",
    28: "Conocer la anatomía de los peces con el fin de controlar su reproducción y captura para alimento.",
    29: "Conocer con detalle las leyes de la herencia y la genética.",
    30: "Conocer el funcionamiento de los órganos del cuerpo humano.",
    31: "Conocer el tratamiento más adecuado para las enfermedades bovinas.",
    32: "Conocer con detalle las técnicas más eficientes de riego y fertilización de la tierra.",
    33: "Trabajar en un vivero dedicado exclusivamente al estudio y a la reproducción de árboles de todo tipo.",
    34: "Asesorar a un grupo de compañías constructoras en el diseño de ubicación de áreas verdes y en el manejo de drenajes de un nuevo asentamiento humano.",
    35: "Usar técnicas para cultivar artificialmente ostiones, almejas, caracoles, camarones, etcétera.",
    36: "Conocer cómo se distribuye la fauna marina.",
    37: "Conocer la estructura y el funcionamiento del ojo humano, sus anomalías y tratamiento.",
    38: "Supervisar en los rastros el estado de salud de las reses que serán sacrificadas.",
    39: "Saber cómo distribuir las instalaciones de un establo para ganado de engorda.",
    40: "Trabajar en un aserradero supervisando la producción de maderas y derivados de los árboles.",
    41: "Proponer, con fundamentos, la construcción de una planta tratadora de aguas residuales en un municipio.",
    42: "Aplicar técnicas de procesado de alimentos de origen marino (peces).",
    43: "Entender las causas y los mecanismos de la emigración de aves y peces.",
    44: "Diseñar un programa para la más rápida recuperación de los enfermos.",
    45: "Investigar los tratamientos más adecuados para el parto en el ganado.",
    46: "Participar en programas de mejoramiento de forrajes y alimentos para la producción del ganado lechero.",
    47: "Estudiar la estructura de los diferentes tipos de árboles de una región selvática y las funciones de la forma en que se relacionan.",
    48: "Ser un experto en el diagnóstico del impacto ambiental que podría causar en el ecosistema una planta termoeléctrica, un hospital o una industria.",
    49: "Trabajar en un buque pesquero como supervisor de calidad de los productos marinos que ahí mismo se enlatan.",
    50: "Conocer las causas de origen biológico que intervienen en la extinción de algunas especies.",
    51: "Participar en un equipo que investigue los efectos del exceso de colesterol en el organismo humano.",
    52: "Cuidar la salud de los animales de una granja.",
    53: "Diseñar nuevos sistemas de irrigación, fecundación y fertilización de hortalizas.",
    54: "Ser un experto en enfermedades y plagas de árboles.",
    55: "Desarrollar, con fundamentos, nuevas leyes que legislen a la industria en el uso de sus residuos, desechos y ubicación para prevenir la contaminación ambiental.",
    56: "Clasificar peces de acuerdo con su valor comercial y alimenticio.",
    57: "Hacer estudios para determinar qué animales están en peligro de extinción.",
    58: "Manejar con destreza el instrumental médico.",
    59: "Conocer las enfermedades de la raza canina y su tratamiento.",
    60: "Crear nueva tecnología para mejorar la producción de la siembra de granos.",
    61: "Conocer a fondo la vida de los bosques y las selvas; además, la manera como interactúan los distintos tipos de árboles.",
    62: "Trabajar en organismos e instituciones dedicadas a la investigación y preservación del medio.",
    63: "Producir alimentos para el hombre con productos del mar.",
    64: "Conocer las teorías existentes acerca de la microbiología.",
    65: "Conocer las diferencias entre la anatomía masculina y la femenina.",
    66: "Hacer inseminaciones artificiales en el ganado.",
    67: "Crear mejores fuentes alimenticias para el ganado.",
    68: "Ser un experto en la industrialización y explotación de los recursos madereros.",
    69: "Proponer nuevas formas de vida urbana, que tengan como fin el beneficio de la Tierra (armonizar, hombre-naturaleza).",
    70: "Supervisar estanques donde existan criaderos de langostino y camarón.",
  };

  final Map<int, String> q = {
    1: "Investigar la composición molecular de cualquier sustancia en un laboratorio dedicado a la investigación.",
    2: "Trabajar para una industria metalúrgica en la obtención de nuevas aleaciones y tipos de metales.",
    3: "Aplicar técnicas químicas para elaborar productos alimenticios, como leche, quesos, jamón, chorizos, sardinas, atún, etcétera.",
    4: "Hacer análisis clínicos en un hospital, para identificar las bacterias que enferman a los individuos.",
    5: "Trabajar para una compañía que produce medicamentos.",
    6: "Producir fertilizantes para árboles frutales y plantas de consumo humano.",
    7: "Diseñar un procedimiento químico para elaborar pinturas con propiedades nuevas.",
    8: "Investigar las diferencias entre química orgánica e inorgánica.",
    9: "Supervisar el proceso químico en una fundidora productora de acero.",
    10: "Conocer de qué manera los microorganismos producen la fermentación de ciertas sustancias para utilizarlos en la elaboración de algunas bebidas.",
    11: "Conocer técnicas químicas para detectar la presencia de algunas enfermedades en el cuerpo humano.",
    12: "Trabajar en un laboratorio productor de medicamentos a base de penicilina.",
    13: "Conocer cómo actúan algunas sustancias químicas en el control de plagas de los sembradíos.",
    14: "Supervisar la calidad de producción en una planta química industrial donde se elaboren aceites y aditivos para motores.",
    15: "Dedicarme a investigar en el laboratorio químico de una universidad y publicar los resultados de dicha investigación.",
    16: "Aplicar las técnicas químicas para obtener sustancias más perdurables en la fabricación de espejos y metales preciosos.",
    17: "Trabajar en el laboratorio químico de una compañía dedicada a producir compuestos necesarios en la elaboración de alimentos.",
    18: "Diseñar un modelo químico que rápidamente y con base en reactivos fáciles de usar en casa sea capaz de detectar: a) el grado de azúcar en la sangre de una persona diabética; b) si hay embarazo, o c) una anormalidad en el organismo.",
    19: "Aplicar técnicas químicas para producir nuevos analgésicos y cierto tipo de drogas.",
    20: "Asesorar a un grupo de agricultores acerca del tipo de sustancias químicas que deben usar en sus sembradíos para el control de plagas.",
    21: "Diseñar un procedimiento químico para lograr plásticos más resistentes.",
    22: "Profundizar en la composición química de los reactivos.",
    23: "Trabajar en una planta química que produzca reactivos para el cemento o materiales de construcción.",
    24: "Supervisar el correcto uso de los conservadores en una empresa dedicada a producir embutidos como salchicha, jamón o productos del mar enlatados.",
    25: "Realizar análisis de microbios en un laboratorio, para combatir epidemias.",
    26: "Investigar una fórmula química que sea capaz de servir como medicamento o tratamiento eficaz contra los trastornos nerviosos.",
    27: "Hacer una investigación para el Gobierno federal respecto a los compuestos químicos ecológicamente más idóneos en el control de las plagas de las hortalizas.",
    28: "Trabajar en una planta química que produzca lacas y barnices.",
    29: "Enseñar química en la universidad.",
    30: "Diseñar nuevos equipos e instrumentos químicos para producir mejores productos de porcelana, barro y cerámica.",
    31: "Conocer el uso de los compuestos químicos en la elaboración de la cerveza.",
    32: "Diseñar un nuevo proceso químico que permita identificar el tipo de bacterias que afectan a un organismo.",
    33: "Realizar trabajos de investigación tendientes a desarrollar fórmulas nuevas y más eficientes en la producción de anticonceptivos, hormonas sintéticas, etcétera.",
    34: "Trabajar en la Secretaría de Agricultura como analista y evaluador de las sustancias que se usan en la prevención de enfermedades de plantas como la tomatera y la patata.",
    35: "Trabajar en una empresa dedicada a la producción de explosivos.",
    36: "Profundizar en todos los grandes descubrimientos químicos.",
    37: "Utilizar las técnicas químicas para producir cobre, zinc, etc., en una siderúrgica.",
    38: "Investigar las propiedades nutritivas de los peces y de los organismos marinos en general.",
    39: "Saber, después de un análisis de microbios a un organismo enfermo, qué tipo de compuesto o fármaco es el adecuado para su tratamiento.",
    40: "Trabajar en un laboratorio químico dedicado a dictaminar la peligrosidad del uso de ciertos fármacos por el hombre.",
    41: "Ser un experto en el diagnóstico y análisis de sustancias químicas que componen el suelo específico para siembra, con el propósito de mejorarlo.",
    42: "Conocer las técnicas de producción de asfaltos e impermeabilizantes.",
    43: "Crear nuevos métodos de análisis químicos y publicarlos.",
    44: "Diseñar un proceso químico para obtener nuevos desinfectantes o bactericidas.",
    45: "Conocer técnicas de conservación química que eviten la descomposición de los alimentos.",
    46: "Estudiar nuevos procedimientos para la detección del cáncer por medio de la orina.",
    47: "Diseñar para una industria un procedimiento químico para producir tratamientos antidiarreicos, antiinfecciosos, etcétera.",
    48: "Hacer análisis de nutrimentos de pastos forrajeros.",
    49: "Trabajar en un laboratorio químico de Petróleos Mexicanos.",
    50: "Investigar fenómenos químicos no explicados todavía.",
    51: "Supervisar en una industria el proceso químico para la elaboración de sales y minerales.",
    52: "Ser un perito del estado químico de los alimentos que están en venta al público.",
    53: "Trabajar en un laboratorio con un grupo de ginecólogos dedicados a hacer pruebas a las pacientes respecto a la existencia de embarazo.",
    54: "Supervisar en una empresa la calidad química de la producción de cremas antisépticas.",
    55: "Trabajar en un laboratorio dedicado a realizar análisis de elementos agrícolas, como suelos, pastos, enfermedades de plantas, etcétera.",
    56: "Trabajar en un laboratorio dedicado a producir nuevas fibras sintéticas derivadas del petróleo.",
    57: "Trabajar en un instituto de ciencias e investigación en química.",
    58: "Trabajar en una empresa vigilando el proceso químico de elaboración de vidrio, aceros, etcétera.",
    59: "Diagnosticar, mediante análisis químicos, la potabilidad del agua.",
    60: "Hacer análisis de sangre a los pacientes de un hospital.",
    61: "Conocer el procedimiento para elaborar fármacos que ayuden a los diabéticos o a cualquier otro tipo de enfermos.",
    62: "Asesorar a un grupo de agricultores acerca del uso correcto de insecticidas y pesticidas.",
    63: "Trabajar en los laboratorios químicos de una empresa dedicada a la fabricación de neumáticos (llantas) para automóviles.",
    64: "Experimentar nuevas fórmulas químicas y posteriormente hacer un informe al respecto para publicarlo en una revista de investigación.",
    65: "Diseñar un procedimiento químico para elaborar aluminio, acero u otro tipo de metales.",
    66: "Conocer técnicas químicas para aprovechar los recursos alimenticios de algunos vegetales.",
    67: "Conocer el procedimiento químico para la detección del virus del SIDA.",
    68: "Diseñar procedimientos para la conservación de algunos fármacos de origen orgánico que serán transportados a grandes distancias.",
    69: "Trabajar en un departamento de análisis, cuya función sea la de controlar la buena calidad de los concentrados que se producen en una empresa de alimentos para ganado.",
    70: "Conocer técnicas químicas para elaborar energéticos como gasolina y diesel.",
  };

  final a = {
    1: "Llevar en computadora los inventarios de una empresa.",
    2: "Hacer las declaraciones fiscales de algunas empresas.",
    3: "Seleccionar personal en un centro de reclutamiento.",
    4: "Trabajar en una compañía dedicada a la distribución de productos novedosos.",
    5: "Administrar una agencia de viajes.",
    6: "Planear los gastos que realizará un municipio.",
    7: "Diseñar una campaña financiera para construir nuevos laboratorios en una universidad.",
    8: "Asesorar a un grupo de campesinos en la comercialización de sus productos.",
    9: "Dirigir una empresa minera.",
    10: "Dirigir un centro computacional donde se maneje la información de un gran centro comercial.",
    11: "Llevar en libros el control de egresos e ingresos de un corporativo.",
    12: "Planear nuevas fórmulas de trabajo para que los empleados de un corporativo se sientan más satisfechos y contentos con sus labores.",
    13: "Planificar campañas para introducir en las principales tiendas del extranjero algunos productos nacionales.",
    14: "Promover turísticamente a la región.",
    15: "Hacer presupuestos al gobierno del estado para campañas sociales.",
    16: "Dirigir una institución educativa.",
    17: "Administrar una propiedad agrícola.",
    18: "Organizar los departamentos que laboren en una oficina dedicada a la explotación de minerales.",
    19: "Someter a prueba nuevos programas computacionales para llevar el control de facturas en una negociación.",
    20: "Realizar trabajos que le demuestren a un corporativo o asociación sus estados financieros, objetivamente.",
    21: "Implementar sistemas de remuneración y premio a los trabajadores, con el fin de que éstos se desempeñen más exitosamente.",
    22: "Asesorar a grandes almacenes haciéndoles estudios que les ayuden a determinar las probabilidades de éxito al abrir un nuevo centro comercial.",
    23: "Diseñar programas que motiven a los huéspedes de un complejo hotelero a regresar.",
    24: "Asesorar a un grupo de gobernantes acerca de cómo utilizar los recursos financieros del Estado.",
    25: "Trabajar en la organización de una institución educativa para el manejo eficiente de las colegiaturas.",
    26: "Trabajar en un banco agrícola implementando programas crediticios que lleven a los agricultores a una mayor optimización de los mismos.",
    27: "Diseñar sistemas de control en el almacenaje de maquinaria y equipo minero.",
    28: "Implementar un sistema computarizado en el que un almacén pueda llevar el control diario en los precios de sus mercancías.",
    29: "Verificar que sea exacta la información de un estado financiero presentado por un despacho de contadores.",
    30: "Investigar la imagen que un centro comercial tiene entre sus clientes.",
    31: "Trabajar en un despacho dedicado a facilitar los trámites aduanales que requieren algunas empresas en la importación y exportación de sus productos.",
    32: "Trabajar en la Secretaría de Turismo.",
    33: "Diseñar modelos administrativos que simplifiquen los servicios del Estado a los contribuyentes.",
    34: "Implementar en una escuela sistemas administrativos más eficientes.",
    35: "Implementar sistemas de comercialización de productos agrícolas, que permitan obtener mayores ganancias a los agricultores.",
    36: "Comercializar los productos de un complejo siderúrgico.",
    37: "Utilizar modernas computadoras para llevar el control de nómina del personal de una empresa.",
    38: "Calcular si una empresa tiene utilidades o pérdidas económicas en su operación.",
    39: "Diseñar programas de capacitación para los empleados de una industria.",
    40: "Supervisar y diseñar campañas publicitarias para los centros comerciales de la región.",
    41: "Diseñar planes de viaje para visitantes extranjeros.",
    42: "Mejorar los procedimientos en las oficinas de pago de impuestos a través de modernos equipos de computación.",
    43: "Trabajar en el departamento de una universidad, cuya labor sea planear e implementar campañas financieras para mejorar las instalaciones de dicha institución.",
    44: "Dirigir una empresa agrícola.",
    45: "Trabajar en un departamento laboral dedicado a contratar personal altamente especializado en los trabajos de extracción y beneficio de minerales.",
    46: "Mantener actualizado a un corporativo con la información de su empresa, con base en la tecnología computacional.",
    47: "Asesorar a un hospital acerca de cómo administrar sus utilidades económicas.",
    48: "Dirigir una nueva empresa turística.",
    49: "Asesorar a un grupo de artesanos en la comercialización de su producción.",
    50: "Fungir como presidente de un complejo hotelero.",
    51: "Hacer presupuestos de gastos en una campaña política.",
    52: "Ocupar un puesto directivo en una universidad prestigiada.",
    53: "Organizar grupos de campesinos para optimizar la compra de implementos para siembra.",
    54: "Hacer estudios de compra de maquinaria y de implementos mineros a una empresa dedicada a la minería.",
    55: "Conocer métodos y técnicas de programación computacional, para llevar el control de entrada y salida de mercancía en una bodega.",
    56: "Asesorar a una asociación de comerciantes para tramitar sus asuntos en la oficina federal de Hacienda.",
    57: "Diseñar un programa para que el producto de una industria sea mejor aceptado por el público (mejorar la imagen).",
    58: "Hacer estudios en la comunidad para determinar qué tipo de productos comerciales tendrán más éxito.",
    59: "Administrar una empresa dedicada al intercambio de tiempos compartidos.",
    60: "Fungir como tesorero en el gobierno del estado.",
    61: "Dirigir a un grupo de maestros que implementarán un programa de mejoramiento académico.",
    62: "Ser parte de una brigada de profesionales que se dediquen a asesorar a un grupo de agricultores en la organización de empresa rurales.",
    63: "Trabajar estableciendo relaciones comerciales entre una compañía productora de materiales extraídos del subsuelo y compradores potenciales.",
    64: "Dirigir el centro de informática (computacional) del Aeropuerto Internacional.",
    65: "Presentar ideas a un corporativo respecto a cómo invertir sus utilidades.",
    66: "Manejar la Ley federal del trabajo para conocer a fondo los derechos y obligaciones de los trabajadores.",
    67: "Hacer estudios para saber qué tipo de transporte resulta más barato y más eficiente para el envío de mercancía entre ciudades.",
    68: "Supervisar en un centro vacacional la buena marcha de los servicios de atención al turismo.",
    69: "Planear de manera más eficiente el control de gastos de los servicios de un municipio, como: policía, recolección de basura y mantenimiento de parques y jardines.",
    70: "Presupuestar los gastos anuales de un escuela de educación superior y vigilar que éstos se apliquen correctamente.",
    71: "Diseñar y proponer a la Secretaría de Agricultura un programa para el impulso de empresas agrícolas.",
    72: "Hacer más fácil y eficiente la organización de las oficinas de una siderúrgica.",
    73: "Buscar nuevas formas de organizar eficientemente la información en oficinas de gobierno.",
    74: "Llevar la contabilidad de una institución educativa.",
    75: "Conocer qué motiva a la gente a realizar mejor su trabajo.",
    76: "Conocer a fondo el derecho mercantil.",
    77: "Proponer campañas para atraer turismo extranjero al país.",
    78: "Trabajar como directivo de la Secretaría de Hacienda y Crédito Público, realizando estudios acerca de la inversión de obras públicas.",
    79: "Fundar una nueva escuela.",
    80: "Llevar la organización de un establo-granja.",
    81: "Hacer cálculos a una compañía minera respecto a los costos de extracción y producción.",
    82: "Hacerse cargo de los sistemas de cómputo-electoral en las campañas políticas.",
    83: "Conocer a fondo el derecho fiscal para asesorar a la planta productiva.",
    84: "Planear programas publicitarios para una compañía.",
    85: "Promover en el extranjero y en el país la comercialización de nuevos productos eléctricos de uso doméstico.",
    86: "Conocer la gastronomía nacional con el propósito de promover el turismo.",
    87: "Supervisar el buen funcionamiento de las oficinas y departamentos que laboran en el gobierno del estado.",
    88: "Supervisar el buen funcionamiento académico de los profesores, de las instalaciones deportivas y de los laboratorios de una escuela.",
    89: "Ser distribuidor de productos agrícolas y ganaderos a establos y granjas.",
    90: "Promover empresas campesinas que se dediquen a la explotación de yacimientos mineros propios de sus tierras.",
  };

  final Map<int, String> s = {
    1: "Conocer cómo afecta a las costumbres de una clase social la religión que profesan los individuos de dicha clase.",
    2: "Ayudar a los enfermos de un hospital.",
    3: "Conocer qué motiva al hombre a comportarse como lo hace.",
    4: "Conocer a fondo cómo ha evolucionado la relación política entre los países latinoamericanos.",
    5: "Conocer detalladamente las técnicas de enseñanza con las cuales los alumnos aprenden mejor del material impartido.",
    6: "Ser portavoz ante los medios de comunicación de los avances científicos de una universidad.",
    7: "Investigar el porqué un grupo de indígenas no quieran hablar español.",
    8: "Platicar con los familiares de los reclusos en un centro penitenciario con el propósito de que formen parte de la rehabilitación de los mismos.",
    9: "Ayudar a alguien que está pasando por un momento difícil.",
    10: "Conocer con detalle el derecho internacional que regula la relación entre los países.",
    11: "Diseñar técnicas de educación para sordos y ciegos.",
    12: "Representar en eventos de la comunidad a un grupo de empresarios.",
    13: "Investigar con detalle los elementos que influyen para la formación de las pandillas que exhiben conductas antisociales.",
    14: "Organizar colectas para los menesterosos e indigentes.",
    15: "Ayudar a las familias en proceso de desintegración a integrarse nuevamente.",
    16: "Defender, con base en el derecho, los intereses de una empresa.",
    17: "Trabajar en una institución educativa diseñando programas para el mejor aprendizaje de los alumnos.",
    18: "Representar a una ciudad dando una cálida recepción a visitantes extranjeros.",
    19: "Investigar los elementos que influyen en un divorcio.",
    20: "Promover cooperativas de consumo entre los más necesitados.",
    21: "Entender cómo evoluciona o se desarrolla mejor la psicología del hombre.",
    22: "Trabajar en una embajada fuera del país y defender, de acuerdo con el derecho, a los indocumentados e inmigrantes.",
    23: "Formar centros de capacitación e instrucción para campesinos.",
    24: "Atender las quejas de los usuarios en una empresa.",
    25: "Investigar los elementos que influyen en ciertos grupos humanos (indígenas o menonitas, por ejemplo), para que éstos no quieran vivir en la ciudad.",
    26: "Servir como tercero en discordia para reconciliar familias.",
    27: "Conocer la psicología profunda del hombre y saber cómo ésta lo lleva a actuar de una manera determinada.",
    28: "Ser un experto en el derecho mercantil, nacional e internacional, para que de esta manera se agilice el comercio.",
    29: "Implementar programas educativos que lleven a los estudiantes a un mejor aprovechamiento de las diferentes disciplinas.",
    30: "Trabajar en un complejo turístico atendiendo a los usuarios, para hacer más agradable su estancia.",
    31: "Investigar las causas y consecuencias sociales de la explosión demográfica.",
    32: "Conseguir donativos para equipar mejor un hospital.",
    33: "Conocer técnicas psicológicas que permitan a los demás conocerse e integrarse mejor.",
    34: "Ser parte de un jurado que determine, basado en el derecho, la culpabilidad o inocencia de alguien.",
    35: "Trabajar en brigadas de alfabetización.",
    36: "Organizar actividades de convivencia (deportivas y culturales), en un complejo turístico.",
    37: "Investigar las causas que llevan a los campesinos a emigrar a Estados Unidos de América.",
    38: "Promover mejores condiciones de vida para los jubilados, y que éstos se sientan bien sin las actividades acostumbradas.",
    39: "Ayudar a los jóvenes a orientarse profesionalmente.",
    40: "Actuar como diputado o senador en la cámara legislativa. Aprobar, desaprobar y diseñar nuevas leyes.",
    41: "Hacer estudios comparativos entre sistemas de enseñanza para determinar cuál es mejor.",
    42: "Mejorar las relaciones humanas en un centro laboral.",
    43: "Investigar por qué en una comunidad hay diferentes formas de practicar la religión.",
    44: "Hacer campañas para recolectar objetos domésticos usados y dárselos a los más necesitados.",
    45: "Conocer a fondo cómo se desarrolla la personalidad e inteligencia del niño.",
    46: "Participar en campañas políticas.",
    47: "Crear programas para niños y adultos que exhiben problemas de aprendizaje.",
    48: "Conocer las causas de una mala comunicación entre los trabajadores de un centro laboral y corregirlas.",
    49: "Investigar la vida matrimonial y familiar de los grupos marginados.",
    50: "Trabajar en una escuela del Estado para integrar a los padres de familia dentro del proceso educativo.",
    51: "Aplicar pruebas que develen la personalidad de otros.",
    52: "Proponer y diseñar nuevas leyes para la regulación del comercio internacional.",
    53: "Supervisar que en una institución educativa se cumplan los programas de estudio.",
    54: "Conocer técnicas para diagnosticar y señalar a un grupo de empresarios los errores y problemas de comunicación que existen entre su empresa y la comunidad.",
    55: "Investigar las formas de vida que caracterizan a las clases sociales altas.",
    56: "Ayudar a los habitantes de colonias pobres a tramitar los servicios de luz, agua, etc., ante el gobierno.",
    57: "Trabajar en la rehabilitación de personas con trastornos psicológicos.",
    58: "Ser experto en el conocimiento de la historia y evolución de los diversos grupos políticos del país.",
    59: "Hacer investigación acerca de las técnicas de enseñanza y aprendizaje (cómo enseñar mejor).",
    60: "Asesorar a una institución de gobierno en la implementación de programas que lleven a sus empleados a mejorar la comunicación y relación entre ellos y los directivos.",
  };

  final h = {
    1: "Conocer por qué y para qué existe el hombre.",
    2: "Dirigir una obra teatral.",
    3: "Escribir en un periódico.",
    4: "Aprender técnicas de fotograbado.",
    5: "Dirigir a un grupo escolar dedicado a realizar bailables folklóricos.",
    6: "Dirigir un coro eclesiástico.",
    7: "Supervisar la información en un periódico.",
    8: "Traducir las grandes obras clásicas de la literatura.",
    9: "Hacer excavaciones en búsqueda de objetos pertenecientes a las civilizaciones antiguas.",
    10: "Trabajar en una biblioteca.",
    11: "Conocer a fondo el pensamiento de Aristóteles, Platón y Marx.",
    12: "Actuar en televisión.",
    13: "Supervisar la redacción y el estilo de los escritos realizados en un periódico.",
    14: "Ser hábil en el manejo de técnicas para construcción de maquetas.",
    15: "Participar en un grupo que investiga bailables y danzas regionales.",
    16: "Realizar composiciones musicales.",
    17: "Elaborar una revista de difusión dentro de la universidad.",
    18: "Hacer doblajes de películas extranjeras.",
    19: "Conocer la forma de vida de los pueblos a través de su religión y arte.",
    20: "Conocer a fondo los sistemas de clasificación de libros.",
    21: "Poder explicar el sentido de la existencia de la vida humana.",
    22: "Dirigir un grupo escolar de teatro.",
    23: "Participar en un jurado que califique un concurso de novela.",
    24: "Dominar las técnicas de acuarela y óleo.",
    25: "Fungir como jurado en un certamen de baile y danza.",
    26: "Ser hábil en el manejo de diversos instrumentos musicales.",
    27: "Producir documentales videograbados.",
    28: "Traducir simultáneamente los trabajos de investigación que se exponen en un congreso internacional de ciencias.",
    29: "Conocer las diferencias y semejanzas en la forma de vida de los diversos grupos indígenas.",
    30: "Asesorar a coleccionistas de libros acerca de cómo organizarlos.",
    31: "Comparar diferentes teorías filosóficas que hablen del hombre, en relación con la religión.",
    32: "Conocer con detalle las nuevas técnicas de dirección teatral.",
    33: "Supervisar la redacción y el estilo de los editoriales de periódicos.",
    34: "Manejar las técnicas de reconstrucción de murales y esculturas.",
    35: "Investigar la historia y evolución de los diferentes bailables y danzas internacionales.",
    36: "Conocer con detalle las posibilidades y limitaciones de diversos instrumentos musicales.",
    37: "Manejar hábilmente las cámaras fotográficas y de cine para producir audiovisuales.",
    38: "Servir como intérprete entre dos personas de diferente nacionalidad.",
    39: "Saber clasificar utensilios, tales como herramientas de caza y de trabajo dejados por nuestros antepasados.",
    40: "Ser experto en clasificación de documentos antiguos.",
    41: "Investigar lo que significa el trabajo para el hombre.",
    42: "Crear nuevos estilos de actuación.",
    43: "Escribir cuentos cortos.",
    44: "Diseñar escenografías para obras teatrales.",
    45: "Participar en un grupo que ejecute danza clásica.",
    46: "Investigar e interpretar la música latinoamericana.",
    47: "Trabajar en un estudio dedicado a la fotografía.",
    48: "Traducir documentos oficiales para los servidores de una embajada.",
    49: "Entender las razones que llevaron a nuestros antepasados a construir sus centros ceremoniales y comerciales de una forma específica.",
    50: "Dirigir o administrar una biblioteca universitaria.",
    51: "Saber en detalle cómo el hombre conoce el mundo que lo rodea.",
    52: "Representar papeles dramáticos y cómicos en un programa de radio.",
    53: "Escribir guiones de teatro con temas de actualidad.",
    54: "Conocer con detalle las técnicas para trabajar piel, vidrio, madera, etcétera.",
    55: "Crear nuevas formas de expresión corporal y musical a través del baile.",
    56: "Enseñar a los niños a solfear.",
    57: "Producir programas televisivos en circuito cerrado dentro de la universidad.",
    58: "Doblar al español series de televisión.",
    59: "Conocer en profundidad las formas de vida de la gente que habita las ciudades perdidas o cinturones de miseria.",
    60: "Ser encargado del cuidado de los libros de un gran monasterio.",
    61: "Escribir un libro en el que analice a fondo el sentido y la razón de la relación entre los seres humanos.",
    62: "Actuar como maestro de ceremonias en un festival de música.",
    63: "Participar en un programa de televisión charlando acerca de los diferentes géneros literarios.",
    64: "Hacer una investigación respecto a la evolución de la artesanía en México.",
    65: "Montar la coreografía para un programa o revista musical.",
    66: "Leer e interpretar notas musicales.",
    67: "Producir audiovisuales con las actividades más importantes del año.",
    68: "Dominar perfectamente tres o más idiomas.",
    69: "Estudiar a fondo la historia y evolución de un pueblo.",
    70: "Hacer visitas de estudio a las más grandes y famosas bibliotecas del mundo, para conocer qué actividades se desarrollan ahí.",
    71: "Conocer las teorías que hablan de Dios como fin último y fundamento del hombre.",
    72: "Ser parte de un jurado que califique la mejor obra teatral.",
    73: "Investigar los diferentes estilos y géneros literarios contenidos en la Biblia.",
    74: "Ser jurado en concursos de logotipos.",
    75: "Dirigir una escuela de danza y baile.",
    76: "Hacer arreglos musicales para un intérprete famoso.",
    77: "Tomar fotografías para una revista de circulación internacional.",
    78: "Trabajar en una editorial haciendo traducciones de obras diversas.",
    79: "Participar en el rescate de construcciones antiguas para reconstruir su historia.",
    80: "Ser un experto en el manejo de colecciones clásicas de libros.",
    81: "Conocer a fondo el fin que persigue el hombre, y la razón de la historia.",
    82: "Investigar y representar teatro de origen indígena.",
    83: "Enseñar redacción y ortografía.",
    84: "Manejar la técnica del dibujo.",
    85: "Dirigir a un grupo de niños que ejecuten rondas infantiles.",
    86: "Ser parte de una sinfónica.",
    87: "Diseñar y producir programas televisivos para niños, con nuevos conceptos de la comunicación.",
    88: "Conocer a fondo la gramática de otros idiomas, como francés, inglés, alemán, etcétera.",
    89: "Hacer revisiones y estudios de documentos y manuscritos antiguos para escribir un artículo de historia.",
    90: "Promover entre el público las visitas a las bibliotecas.",
    91: "Enseñar la materia de filosofía en una universidad prestigiada.",
    92: "Dirigir telenovelas de alta calidad.",
    93: "Hacer conciencia en la gente de lo importante que es el uso correcto del lenguaje escrito.",
    94: "Ser hábil en el uso de herramientas de dibujo y modelado.",
    95: "Organizar un programa para que la gente tome conciencia de la importancia de la danza y del baile.",
    96: "Componer y ejecutar música con aparatos electrónicos.",
    97: "Manejar las teorías de la comunicación humana.",
    98: "Ayudar a estudiantes de posgrado en la traducción de materiales científicos.",
    99: "Investigar las diferentes maneras de como los diversos grupos sociales ofrecen culto a sus muertos.",
    100: "Conocer a fondo el manejo de una biblioteca.",
  };



